import {Runtime} from '../plc/runtime';
import {parseProgram} from '../plc/compiler';
import type {PlantKind} from '../challenges/catalog';
import {Plant} from './conveyor';
import type {Scalar} from '../plc/model';
let runtime:Runtime|undefined,plant=new Plant(),mode:'RUN'|'PAUSE'|'STOP'|'ERROR'='STOP',speed=1,budget=0,kind='motor',cycle=0;
const emit=(error?:string)=>postMessage({snapshot:runtime?.snapshot(),plant:plant.snapshot(),mode,cycle,error});
function scan(){if(!runtime)return;const start=performance.now();if(plant.auto){if(['water','mixer','roaster'].includes(kind)){for(const [tag,value] of Object.entries(plant.inputs()))if(tag in runtime.inputs)runtime.inputs[tag]=value;}if('SENSOR'in runtime.inputs)runtime.inputs.SENSOR=plant.sensor();if(kind==='tank'){if('RAW'in runtime.inputs)runtime.inputs.RAW=Math.round(plant.temperature/150*27648);if('LOW'in runtime.inputs)runtime.inputs.LOW=plant.level<=20;if('HIGH'in runtime.inputs)runtime.inputs.HIGH=plant.level>=85;if('EMPTY'in runtime.inputs)runtime.inputs.EMPTY=plant.level<=10;}}runtime.scan(10);plant.step(10,runtime.outputs);cycle=performance.now()-start;}
onmessage=(event:MessageEvent<{action:string;program?:unknown;tag?:string;value?:Scalar|null;speed?:number;auto?:boolean;fault?:Plant['fault'];plant?:PlantKind;faultTarget?:string}>)=>{const m=event.data;try{switch(m.action){case'clear':runtime=undefined;kind=m.plant??'motor';plant=new Plant(m.plant??'motor');mode='STOP';budget=0;break;case'load':runtime=new Runtime(parseProgram(m.program));kind=m.plant??'motor';plant=new Plant(m.plant??'motor');mode='STOP';budget=0;break;case'run':if(runtime)mode='RUN';break;case'pause':mode='PAUSE';break;case'stop':mode='STOP';runtime?.stop();break;case'step':if(runtime){mode='PAUSE';scan();}break;case'speed':if([.25,.5,1,2,5].includes(m.speed??0))speed=m.speed!;break;case'input':if(runtime&&m.tag&&m.value!==null&&m.value!==undefined){const t=runtime.memory.tags.get(m.tag);if(!t?.address.startsWith('%I'))throw Error('Yalnızca girişler değiştirilebilir');runtime.memory.set(m.tag,m.value);runtime.inputs[m.tag]=m.value;}break;case'force':if(runtime&&m.tag){if(m.value===null)delete runtime.forces[m.tag];else if(m.value!==undefined){runtime.memory.set(m.tag,m.value);runtime.forces[m.tag]=m.value;}}break;case'process-reset':if(runtime)runtime=new Runtime(runtime.program);mode='STOP';budget=0;plant=new Plant(kind as PlantKind);break;case'plant':plant.faultTarget=m.faultTarget??plant.faultTarget;plant.auto=m.auto??plant.auto;plant.fault=m.fault??plant.fault;break;case'product':plant.position=.10;break;}emit();}catch(e){mode='ERROR';runtime?.stop();emit(String(e));}};
setInterval(()=>{if(mode!=='RUN'||!runtime)return;try{budget+=20*speed;while(budget>=10){scan();budget-=10;}emit();}catch(e){mode='ERROR';runtime.stop();emit(String(e));}},20);

