'use client';
import {useState} from 'react';
import {Progress} from '@/components/ui/progress';
import {modulesFor} from '../learning/curriculum';
import {catalogFor,conceptLabel} from '../challenges/catalog';
import {useLang,useT} from '../i18n/react';
import {learningDict} from '../i18n/dict/learning';
import type {Attempt} from './useLab';
export function Learning({attempts,load}:{attempts:Attempt[];load:(id:number,seed?:number,debug?:boolean)=>void}){const t=useT(learningDict),{lang}=useLang(),catalog=catalogFor(lang),modules=modulesFor(lang);const [selected,setSelected]=useState(0);const concepts=[...new Set(catalog.flatMap(c=>c.concepts))];const module=modules[selected];return <div className="learning"><h1>{t('learning.title')}</h1><p>{t('learning.flow')}</p><div className="industrial-exercises">{catalog.filter(c=>c.id>=21).map(c=><button key={c.id} onClick={()=>load(c.id)}><b>{c.title}</b><span>L{c.level} · {c.concepts.map(x=>conceptLabel(x,lang)).join(" / ")}</span><small>{t('learning.openExercise')}</small></button>)}</div><div className="mastery-grid">{concepts.map(c=>{const rows=attempts.filter(a=>(JSON.parse(a.concepts) as string[]).includes(c));const avg=rows.length?Math.round(rows.reduce((a,b)=>a+b.score,0)/rows.length):null;return <div key={c}><span>{conceptLabel(c,lang)}</span><b>{avg===null?'—':`${avg}%`}</b><Progress value={avg??0}/><small>{t(rows.length===1?'learning.attempts.one':'learning.attempts.other',{count:rows.length})}</small></div>;})}</div><div className="course-layout"><div>{modules.map(({title},i)=><button className={selected===i?'active':''} onClick={()=>setSelected(i)} key={title}><span>{String(i+1).padStart(2,'0')}</span>{title}</button>)}</div><article><span className="eyebrow">{t('learning.module',{n:selected+1})}</span><h2>{module.title}</h2><p>{module.body}</p><div className="note">{t('learning.note')}</div><button onClick={()=>load(module.exercise)}>{t('learning.guided')}</button><button onClick={()=>load(module.exercise,Math.floor(Math.random()*999999))}>{t('learning.variant')}</button><button onClick={()=>load(12)}>{t('learning.industrial')}</button><button onClick={()=>load(3,0,true)}>{t('learning.debug')}</button></article></div></div>;}
