'use client';
import {useState} from 'react';
import {Activity,ChevronRight,CircleHelp,Cpu,FileCode2,FilePlus2,FolderOpen,Footprints,MonitorSmartphone,Network,PackageCheck,Play,Stethoscope} from 'lucide-react';
import type {Block} from '../plc/model';
import type {Challenge} from '../challenges/catalog';
import {catalog} from '../challenges/catalog';

// TIA Portal view: task portals on the left, portal actions in the middle, the selected action on the right.
export type ProjectTarget={view:string;block?:string;monitor?:boolean};
type PortalId='start'|'devices'|'plc'|'hmi'|'online';
type Action={id:string;label:string;icon:typeof Play};
const portals:{id:PortalId;label:string;icon:typeof Play}[]=[{id:'start',label:'Start',icon:Play},{id:'devices',label:'Devices & networks',icon:Network},{id:'plc',label:'PLC programming',icon:FileCode2},{id:'hmi',label:'Visualization',icon:MonitorSmartphone},{id:'online',label:'Online & Diagnostics',icon:Stethoscope}];
const actions:Record<PortalId,Action[][]>={
 start:[[{id:'open',label:'Open existing project',icon:FolderOpen},{id:'create',label:'Create new project',icon:FilePlus2}],[{id:'first',label:'First steps',icon:Footprints}],[{id:'software',label:'Installed software',icon:PackageCheck},{id:'help',label:'Help',icon:CircleHelp}]],
 devices:[[{id:'devices',label:'Show all devices',icon:Cpu},{id:'add-device',label:'Change device',icon:FilePlus2}]],
 plc:[[{id:'blocks',label:'Show all objects',icon:FileCode2}]],
 hmi:[[{id:'screens',label:'Show all screens',icon:MonitorSmartphone}]],
 online:[[{id:'accessible',label:'Accessible devices',icon:Activity}]],
};
const cpus=['1211C','1212C','1214C','1215C','1217C'].map(v=>`CPU ${v} DC/DC/DC`);
const blockName=(b:Block)=>b.id==='OB1'?'Main':b.id==='OB100'?'Startup':b.id;

interface Props {visible?:boolean;projectName:string;cpu:string;blocks:Block[];challenge:Challenge;mode:string;locked:boolean;saved:boolean;dirty?:boolean;message?:string;onOpen:(target?:ProjectTarget)=>void;onCreate:(id:number)=>void;onCpu:(cpu:string)=>void;onStart:()=>void;onStop:()=>void}

export default function PortalView({visible=true,projectName,cpu,blocks,challenge,mode,locked,saved,dirty=false,message='',onOpen,onCreate,onCpu,onStart,onStop}:Props){
 const [portal,setPortal]=useState<PortalId>('start'),[last,setLast]=useState<Record<PortalId,string>>({start:'first',devices:'devices',plc:'blocks',hmi:'screens',online:'accessible'}),[template,setTemplate]=useState(challenge.id),[device,setDevice]=useState(cpu),[confirm,setConfirm]=useState<number|null>(null);
 const action=last[portal];
 // Each portal remembers its last action, as TIA does; forms start from the current project state.
 const setAction=(id:string,p:PortalId=portal)=>{setLast(l=>({...l,[p]:id}));setConfirm(null);if(id==='create')setTemplate(challenge.id);if(id==='add-device')setDevice(cpu);};
 const choose=(id:PortalId)=>{setPortal(id);setConfirm(null);};
 const create=(id:number)=>{if(locked)return;if(dirty)setConfirm(id);else onCreate(id);};
 const title=actions[portal].flat().find(a=>a.id===action)?.label??'';
 const content=()=>{switch(action){
  case 'first':return <><p className="portal-lead">Project “{projectName}” was opened successfully. Please select the next step:</p><div className="portal-steps">
   {[{p:'devices' as const,a:'devices',label:'Devices & networks',text:'Configure a device',icon:Network},{p:'plc' as const,a:'blocks',label:'PLC programming',text:'Write PLC program',icon:FileCode2},{p:'hmi' as const,a:'screens',label:'Visualization',text:'Configure an HMI screen',icon:MonitorSmartphone},{p:'online' as const,a:'accessible',label:'Online & Diagnostics',text:'Simulate and monitor the CPU',icon:Stethoscope}].map(s=><button key={s.p} className="portal-step" onClick={()=>{setPortal(s.p);setAction(s.a,s.p);}}><s.icon size={30} strokeWidth={1.4}/><span><b>{s.label}</b>{s.text}</span><ChevronRight size={18}/></button>)}
   <button className="portal-step project" onClick={()=>onOpen()}><FolderOpen size={30} strokeWidth={1.4}/><span><b>Project view</b>Open the project view</span><ChevronRight size={18}/></button></div></>;
  case 'open':return <><h3>Recently used</h3><table className="portal-table"><thead><tr><th>Project</th><th>Path</th><th>Exercise</th><th>Status</th></tr></thead><tbody><tr className="selected" onDoubleClick={()=>onOpen()}><td><FolderOpen size={14}/> {projectName}</td><td>Browser session (server-side save)</td><td>{String(challenge.id).padStart(2,'0')} · {challenge.title}</td><td>{saved?'Saved':'Modified'}</td></tr></tbody></table><div className="portal-buttons"><button className="portal-primary" onClick={()=>onOpen()}>Open</button></div></>;
  case 'create':return <><p className="portal-lead">Each project starts from an industrial exercise. The exercise defines the PLC tags (I/O contract); you write the LAD program.</p><div className="portal-scroll"><table className="portal-table"><thead><tr><th>No.</th><th>Industrial exercise</th><th>Level</th><th>Concepts</th></tr></thead><tbody>{catalog.map(x=><tr key={x.id} className={template===x.id?'selected':''} onClick={()=>{setTemplate(x.id);setConfirm(null);}} onDoubleClick={()=>create(x.id)}><td>{String(x.id).padStart(2,'0')}</td><td>{x.title}</td><td>L{x.level}</td><td>{x.concepts.join(', ')}</td></tr>)}</tbody></table></div>{confirm!==null?<div className="portal-buttons portal-confirm" role="alertdialog" aria-label="Replace current program"><span>The current program is saved once, then replaced by exercise {String(confirm).padStart(2,'0')} with an empty Main [OB1]. Undo history is cleared.</span><button onClick={()=>setConfirm(null)}>Cancel</button><button className="portal-primary" onClick={()=>{setConfirm(null);onCreate(confirm);}}>Create anyway</button></div>:<div className="portal-buttons"><span>{locked?'Stop the CPU before creating a new project.':`Creates a new “${projectName}” with an empty Main [OB1].`}</span><button className="portal-primary" disabled={locked} onClick={()=>create(template)}>Create</button></div>}</>;
  case 'software':return <table className="portal-table"><thead><tr><th>Software</th><th>Version</th><th>Scope</th></tr></thead><tbody><tr><td>PLC Lab Web</td><td>0.1.0</td><td>Engineering workspace (training)</td></tr><tr><td>LAD editor</td><td>0.1.0</td><td>Bit logic, timers, counters, compare, move, math, conversion</td></tr><tr><td>Virtual CPU</td><td>0.1.0</td><td>S7-1200 training profile · 10 ms deterministic scan · OB100 → OB1</td></tr><tr><td>Process simulation</td><td>0.1.0</td><td>Conveyor, tank, water transfer, mixer, roaster</td></tr></tbody></table>;
  case 'help':return <ol className="portal-help"><li>Start → Create new project: choose an industrial exercise.</li><li>PLC programming → Main [OB1]: build the network from the Instructions task card.</li><li>Compile, then RUN the virtual CPU. Monitor shows power flow: green solid = fulfilled, blue dashed = not fulfilled.</li><li>Visualization → HMI_1: operate the process with START / STOP and sensors.</li><li>Test et runs the private timed test suite and scores the program.</li></ol>;
  case 'devices':return <><table className="portal-table"><thead><tr><th>Device</th><th>Type</th><th>Interface</th><th>Status</th></tr></thead><tbody><tr className="selected" onDoubleClick={()=>onOpen({view:'device'})}><td><Cpu size={14}/> PLC_1</td><td>{cpu}</td><td>Virtual (browser)</td><td>{mode}</td></tr><tr onDoubleClick={()=>onOpen({view:'process'})}><td><MonitorSmartphone size={14}/> HMI_1</td><td>Process screens</td><td>Internal tags</td><td>—</td></tr></tbody></table><div className="portal-buttons"><button className="portal-primary" onClick={()=>onOpen({view:'device'})}>Open the device view</button></div></>;
  case 'add-device':return <><p className="portal-lead">Select the CPU for PLC_1. All profiles share the training memory model.</p><div className="portal-device-list">{cpus.map(v=><label key={v} className={device===v?'selected':''}><input type="radio" name="portal-cpu" checked={device===v} onChange={()=>setDevice(v)}/><Cpu size={16}/>{v}</label>)}</div><div className="portal-buttons"><span>{locked?'Stop the CPU before changing the device.':''}</span><button className="portal-primary" disabled={locked||device===cpu} onClick={()=>onCpu(device)}>Change</button></div></>;
  case 'blocks':return <><table className="portal-table"><thead><tr><th>Name</th><th>Number</th><th>Type</th><th>Language</th><th>Networks</th></tr></thead><tbody>{blocks.map(b=><tr key={b.id} onDoubleClick={()=>onOpen({view:'ladder',block:b.id})}><td><FileCode2 size={14}/> {blockName(b)}</td><td>{b.id.replace(/\D/g,'')}</td><td>Organization block</td><td>LAD</td><td>{b.networks.length}</td></tr>)}</tbody></table><div className="portal-buttons"><span>Double-click a block to open it.</span><button className="portal-primary" onClick={()=>onOpen({view:'ladder',block:'OB1'})}>Open Main [OB1]</button></div></>;
  case 'screens':return <><table className="portal-table"><thead><tr><th>Screen</th><th>Device</th><th>Process</th></tr></thead><tbody><tr className="selected" onDoubleClick={()=>onOpen({view:'process'})}><td><MonitorSmartphone size={14}/> Process screens</td><td>HMI_1</td><td>{challenge.title}</td></tr></tbody></table><div className="portal-buttons"><button className="portal-primary" onClick={()=>onOpen({view:'process'})}>Open screen</button></div></>;
  case 'accessible':return <><table className="portal-table"><thead><tr><th>Device</th><th>Device type</th><th>Interface</th><th>Operating mode</th></tr></thead><tbody><tr className="selected"><td><Cpu size={14}/> PLC_1</td><td>{cpu}</td><td>Virtual CPU (Web Worker)</td><td className={mode==='RUN'?'portal-run':'portal-stop'}>● {mode}</td></tr></tbody></table><div className="portal-buttons"><button disabled={mode==='RUN'} onClick={onStart}>Start CPU</button><button disabled={mode!=='RUN'} onClick={onStop}>Stop CPU</button><button className="portal-primary" onClick={()=>onOpen({view:'ladder',block:'OB1',monitor:true})}>Go online · monitor OB1</button></div>{message&&<p className="portal-note" role="status">{message}</p>}</>;
  default:return null;}};
 return <div className="portal" hidden={!visible} role="application" aria-label="Portal view">
  <header className="portal-head"><div className="portal-brand"><span>PLC Lab Web</span><b>S7-1200 TRAINER</b></div></header>
  <div className="portal-body">
   <nav className="portal-tasks" aria-label="Portals">{portals.map(p=><button key={p.id} className={portal===p.id?'active':''} aria-pressed={portal===p.id} onClick={()=>choose(p.id)}><span className="portal-icon"><p.icon size={28} strokeWidth={1.5}/></span>{p.label}</button>)}</nav>
   <nav className="portal-actions" aria-label={`${portals.find(p=>p.id===portal)?.label} actions`}>{actions[portal].map((group,i)=><div key={i} className="portal-action-group">{group.map(a=><button key={a.id} className={action===a.id?'active':''} aria-pressed={action===a.id} onClick={()=>setAction(a.id)}><a.icon size={16}/>{a.label}</button>)}</div>)}</nav>
   <section className="portal-content" aria-label={title}><h2>{title}</h2>{content()}</section>
  </div>
  <footer className="portal-foot"><button className="portal-switch" onClick={()=>onOpen()}><ChevronRight size={16}/>Project view</button><span>Opened project: {projectName} · {String(challenge.id).padStart(2,'0')} {challenge.title}</span></footer>
 </div>;
}
