'use client';
import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';

type Sizes={left:number;right:number;bottom:number};
const defaults:Sizes={left:.22,right:.24,bottom:.32};
const bounds={left:[.12,.35],right:[.14,.35],bottom:[.15,.65]} as const;
const clamp=(key:keyof Sizes,value:number)=>Math.max(bounds[key][0],Math.min(bounds[key][1],value));
export default function ResizableWorkspace({children,className,right,bottomOpen,onOpenBottom,maximized=false}:{maximized?:boolean;children:ReactNode;className:string;right:boolean;bottomOpen:boolean;onOpenBottom:()=>void}){
 const root=useRef<HTMLDivElement>(null),active=useRef<keyof Sizes|null>(null);
 const [sizes,setSizes]=useState(defaults),[ready,setReady]=useState(false),[dragging,setDragging]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('plc-panel-sizes')??'null');if(saved)setSizes(Object.fromEntries(Object.keys(defaults).map(k=>{const key=k as keyof Sizes;return [key,typeof saved[key]==='number'&&Number.isFinite(saved[key])?clamp(key,saved[key]):defaults[key]];})) as Sizes);}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready&&!dragging)try{localStorage.setItem('plc-panel-sizes',JSON.stringify(sizes));}catch{}},[sizes,ready,dragging]);
 const update=(key:keyof Sizes,value:number)=>setSizes(s=>({...s,[key]:clamp(key,value)}));
 const style={'--panel-left':`${sizes.left*100}%`,'--panel-right':right?`${sizes.right*100}%`:'0%','--panel-bottom':bottomOpen?`${sizes.bottom*100}%`:'30px'} as CSSProperties;
 return <div ref={root} className={`${className} resizable-workspace${maximized?' workarea-maximized':''}${dragging?' resizing-panels':''}`} style={style}>{children}{(['left',...(right?['right']:[]),'bottom'] as (keyof Sizes)[]).map(key=><div key={key} className={`panel-splitter splitter-${key}`} role="separator" tabIndex={0} aria-label={key==='left'?'Proje ağacı genişliği':key==='right'?'Sağ panel genişliği':'Alt panel yüksekliği'} aria-orientation={key==='bottom'?'horizontal':'vertical'} aria-valuemin={bounds[key][0]*100} aria-valuemax={bounds[key][1]*100} aria-valuenow={Math.round(sizes[key]*100)} title="Boyutlandırmak için sürükle · Çift tık: varsayılan boyut" onDoubleClick={()=>update(key,defaults[key])} onPointerDown={event=>{event.preventDefault();active.current=key;setDragging(true);event.currentTarget.setPointerCapture(event.pointerId);if(key==='bottom')onOpenBottom();}} onPointerMove={event=>{if(active.current!==key||!root.current)return;const b=root.current.getBoundingClientRect();update(key,key==='left'?(event.clientX-b.left)/b.width:key==='right'?(b.right-event.clientX)/b.width:(b.bottom-event.clientY)/b.height);}} onPointerUp={event=>{active.current=null;setDragging(false);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);}} onPointerCancel={()=>{active.current=null;setDragging(false);}} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(event.key))return;event.preventDefault();if(key==='bottom')onOpenBottom();const increase=key==='left'?event.key==='ArrowRight':key==='right'?event.key==='ArrowLeft':event.key==='ArrowUp';update(key,event.key==='Home'?defaults[key]:sizes[key]+(increase?.02:-.02));}}/>)}</div>;
}
