import type {Tag,Program} from '../plc/model';
export type PlantKind='conveyor'|'tank'|'motor'|'water'|'mixer'|'roaster';
export interface Challenge {id:number;seed:number;title:string;level:number;scenario:string;objectives:string[];concepts:string[];tags:Tag[];delay:number;preset:number;plant:PlantKind;hints:string[]}
const definitions:[string,number,string,string[],string[],string[],string[]][]=[
 ['AND gate',1,'Pres yalnızca iki el butonu birlikte aktifken çalışmalıdır.',['İki buton birlikte TRUE ise MOTOR çalışsın.','Tek buton bırakılınca motor dursun.'],['AND'],['START','ENABLE'],['MOTOR']],
 ['OR gate',1,'Operatör bandı iki farklı istasyondan çalıştırabilir.',['START veya REMOTE aktifse MOTOR çalışsın.','İkisi de bırakılırsa dursun.'],['OR'],['START','REMOTE'],['MOTOR']],
 ['Motor Start / Stop',1,'Bir üretim bandının motorunu START ile çalıştır. Butonu bıraktığında motor çalışmaya devam etsin.',['START motoru çalıştırmalı.','START bırakıldığında motor durumunu korumalı.','STOP motoru durdurmalı; START ile aynı anda verilirse STOP öncelikli.','OVERLOAD motoru durdurmalı ve yeni başlatmayı engellemeli.','Arıza kalktığında motor kendiliğinden başlamamalı.'],['Seal-in','Interlocks'],['START','STOP','OVERLOAD'],['MOTOR']],
 ['Motor seal-in',1,'Bir pompa motoru kısa START darbesi ile sürekli çalıştırılacak.',['START bırakıldığında MOTOR çalışmaya devam etsin.','STOP ve OVERLOAD mühürlemeyi kessin.','Arıza giderildiğinde yeniden START gereksin.'],['Seal-in'],['START','STOP','OVERLOAD'],['MOTOR']],
 ['Emergency stop',1,'Bir test hücresinin kontrol yazılımındaki durdurma mantığını incele.',['START ile mühürle.','E_STOP veya STOP aktifken MOTOR kapansın.','E_STOP kalkınca otomatik yeniden çalışma olmasın.'],['Interlocks','Safety'],['START','STOP','E_STOP'],['MOTOR']],
 ['Forward / reverse interlock',2,'Bir tahrik motoru iki yönde çalışabilir. İki kontaktör birlikte çekmemelidir.',['FWD_CMD ile FORWARD mühürlensin; REV_CMD ile REVERSE mühürlensin.','Karşı yön çalışırken diğer yöne geçilmesin.','İki komut birlikte verilirse iki çıkış da kapalı kalsın.','STOP iki yönü durdursun.'],['Interlocks','Seal-in'],['FWD_CMD','REV_CMD','STOP'],['FORWARD','REVERSE']],
 ['TON motor delay',2,'Fan kontaktörü START sürekli basılı kaldıktan sonra çekmelidir.',['START kesintisiz {delay} ms TRUE olduğunda MOTOR çalışsın.','START bırakılınca çıkış ve timer sıfırlansın.','OVERLOAD aktifken timer ve motor kapalı olsun.'],['Timers'],['START','OVERLOAD'],['MOTOR']],
 ['TOF fan',2,'Havalandırma fanı komut kesildikten sonra bir süre soğutmaya devam eder.',['START ile FAN hemen çalışsın.','START kesildikten {delay} ms sonra FAN dursun.','Tekrar START verilirse kapanma gecikmesi sıfırlansın.'],['Timers'],['START'],['FAN']],
 ['TP pulse',2,'Bir işaretleme valfi tetikleme kenarında sabit süre çalışır.',['START yükselen kenarında VALVE {delay} ms aktif olsun.','START erken bırakılsa da darbe tamamlansın.','START basılı tutulduğunda darbe tekrarlanmasın.'],['Timers','Edges'],['START'],['VALVE']],
 ['Product counter',2,'Paketleme hattı hedef ürün sayısına ulaşınca operatöre haber verir.',['SENSOR yükselen kenarlarını say.','{preset} üründe DONE aktif olsun.','SENSOR sürekli TRUE iken yalnızca bir sayım olsun.','RESET sayacı ve DONE çıkışını sıfırlasın.'],['Counters','Edges'],['SENSOR','RESET'],['DONE']],
 ['Conveyor sensor',2,'Bant üzerindeki ürün kontrol istasyonuna geldiğinde hareket kesilir.',['START ile CONVEYOR mühürlensin.','SENSOR TRUE olduğunda conveyor dursun, sensör temizlenince otomatik devam etsin.','STOP ve OVERLOAD bütün hareketi durdursun.'],['Seal-in','Interlocks'],['START','STOP','SENSOR','OVERLOAD'],['CONVEYOR']],
 ['Conveyor + cylinder',3,'Ürün algılanınca bant duracak; gecikmeli itici ürünü ayırıp bandı yeniden başlatacak.',['START ile conveyor çalışsın; STOP ve OVERLOAD bütün hareketi kessin.','SENSOR yükselen kenarında bant dursun.','{delay} ms bekle; PUSHER 500 ms aktif olsun.','PUSHER kapanınca bant yeniden çalışsın.','SENSOR takılı TRUE kalırsa ikinci darbe oluşmasın.'],['Timers','Sequence','Edges'],['START','STOP','SENSOR','OVERLOAD'],['CONVEYOR','PUSHER']],
 ['Traffic lights',3,'Fabrika içi tek yönlü geçiş için üç lambalı çevrim oluştur.',['START ile çevrim mühürlensin; STOP ile bütün lambalar kapansın.','GREEN {delay} ms, AMBER {delay} ms, RED {delay} ms sırayla yansın.','Çevrim tekrarlansın; aynı anda tek lamba yansın.'],['Timers','Sequence'],['START','STOP'],['GREEN','AMBER','RED']],
 ['Tank filling',3,'Tank alt seviye şalterinden başlayarak üst seviyeye kadar doldurulacak.',['LOW TRUE ve HIGH FALSE ise VALVE açılsın.','LOW sinyali kalksa da dolum devam etsin.','HIGH veya FAULT TRUE olunca VALVE kapansın.'],['Seal-in','Interlocks'],['LOW','HIGH','FAULT'],['VALVE']],
 ['Tank drain',3,'Tank üst seviyeye ulaştığında alt seviyeye kadar boşaltılacak.',['HIGH TRUE ve EMPTY FALSE ise PUMP çalışsın.','HIGH kalksa da PUMP çalışmaya devam etsin.','EMPTY veya FAULT aktifse PUMP dursun.'],['Seal-in','Interlocks'],['HIGH','EMPTY','FAULT'],['PUMP']],
 ['Pump dry-run protection',2,'Transfer pompası su yokken çalışmamalı.',['START ve WATER_OK ile PUMP mühürlensin.','WATER_OK kaybı veya STOP pompayı durdursun.','Su geri geldiğinde START olmadan çalışmasın.'],['Interlocks','Safety'],['START','STOP','WATER_OK'],['PUMP']],
 ['Temperature heater',4,'0–10 V sıcaklık vericisi 0–150 °C aralığını 0–27648 ham değere dönüştürür.',['RAW değerini TEMP (REAL) °C değerine ölçekle.','TEMP < 70 olduğunda HEATER açılsın.','TEMP > 75 olduğunda HEATER kapansın; 70–75 aralığında önceki durumu korusun.','Ham değer 0–27648 dışında veya FAULT TRUE ise heater kapansın.'],['Analog','Hysteresis'],['FAULT'],['HEATER']],
 ['Analog scaling',4,'Bir sıcaklık vericisinin ham değerini mühendislik birimine dönüştür.',['RAW 0–27648 değerini TEMP 0–150 °C aralığına ölçekle.','18432 ham değer için 100 °C hesaplanmalı.','Ara değerlerde REAL hassasiyetini koru.'],['Analog'],[],[]],
 ['Star-delta starter',5,'Motor başlangıçta yıldız, açık geçiş beklemesinden sonra üçgen çalışır.',['START ile ana MOTOR mühürlensin; STOP ve OVERLOAD bütün çıkışları kessin.','STAR ilk {delay} ms aktif olsun.','STAR kapandıktan 100 ms sonra DELTA çalışsın.','STAR ve DELTA hiçbir zaman birlikte aktif olmasın.'],['Timers','Interlocks','Sequence'],['START','STOP','OVERLOAD'],['MOTOR','STAR','DELTA']],
 ['Conveyor sorting',3,'Bant üzerindeki büyük ürünler itici ile ayrılır.',['START ile çalışma iznini mühürle.','SENSOR ve LARGE birlikte aktifken CONVEYOR dursun ve PUSHER çalışsın.','Küçük ürünlerde conveyor devam etsin; PUSHER kapalı kalsın.','STOP veya OVERLOAD bütün hareketi kessin.'],['Interlocks','AND'],['START','STOP','SENSOR','OVERLOAD','LARGE'],['CONVEYOR','PUSHER']],
];
definitions.push(
 ['Su tankı · dolum ve transfer',3,'Bir parti suyu üst seviyeye kadar doldur, ardından tankı boşalt. Şalterler tankın gerçek simülasyon seviyesinden gelir.',['START ile çevrim mühürlensin; STOP veya FAULT çevrimi iptal etsin.','Önce VALVE ile HIGH seviyesine kadar doldur; sonra PUMP ile EMPTY seviyesine kadar boşalt.','VALVE ve PUMP aynı anda çalışmasın.','Boşaltma bitince DONE kalıcı yansın. RESET tamamlandı bilgisini temizlesin; yeni START gereksin.'],['Sequence','Seal-in','Interlocks'],['START','STOP','RESET','FAULT','LOW','HIGH','EMPTY'],['VALVE','PUMP','DONE']],
 ['Boya karıştırma · iki bileşenli parti',4,'A ve B bileşenlerini ayrı valflerle dozajla. Hedefler tamamlanınca kapalı kapakta karıştır, sonra ürünü boşalt.',['START ve LID_CLOSED ile çevrim başlasın; STOP, FAULT veya kapak açılması bütün çıkışları durdursun.','A_READY olana kadar DOSE_A, B_READY olana kadar DOSE_B çalışsın.','İki bileşen tamamlanınca MIXER {delay} ms çalışsın; dozaj valfleri kapalı kalsın.','Karıştırma bitince DRAIN açılsın. EMPTY ile DONE kalıcı yansın ve bütün aktüatörler dursun.','RESET tamamlandı bilgisini temizlesin. Kapak kapanınca START olmadan yeniden çalışma olmasın.'],['Sequence','Timers','Interlocks'],['START','STOP','RESET','FAULT','LID_CLOSED','A_READY','B_READY','EMPTY'],['DOSE_A','DOSE_B','MIXER','DRAIN','DONE']],
 ['Çerez kavurma · ısıtma ve soğutma',5,'Yüklü tamburu döndürerek 120 °C hedefine ulaş, beklet, soğut ve boşalt. Eğitim modeli gerçek ürün reçetesi değildir.',['START ve LID_CLOSED ile DRUM çalışsın; STOP, FAULT veya açık kapak çevrimi iptal etsin.','HOT FALSE iken HEATER açılsın. İlk HOT sinyalinden itibaren {delay} ms kavurma süresi sayılsın.','Süre sonunda HEATER kapansın; COOL olana kadar FAN çalışsın ve DRUM dönmeye devam etsin.','COOL ile DISCHARGE açılsın; EMPTY ile DONE kalıcı yansın ve çıkışlar dursun.','RESET DONE bilgisini temizlesin. Arıza kalkınca START olmadan yeniden çalışma olmasın.'],['Sequence','Timers','Interlocks','Temperature'],['START','STOP','RESET','FAULT','LID_CLOSED','HOT','COOL','EMPTY'],['DRUM','HEATER','FAN','DISCHARGE','DONE']]
);
definitions.push(
 ['İki pompa · dönüşümlü çalışma',4,'Her yeni talepte diğer pompayı seçerek çalışma sayısını paylaş. Seçilen pompa arızalıysa sağlam pompayı kullan.',['İlk DEMAND talebinde PUMP_A çalışsın. Talep bitince sonraki seçim B olsun; her tamamlanan talepte seçim değişsin.','Talep sürekli TRUE iken seçim değişmesin. Aynı anda yalnızca bir pompa çalışsın.','FAULT_A veya FAULT_B seçilen pompayı engellesin; sağlam pompa devralsın. İki arızada ve STOP ile iki çıkış da kapansın.'],['Edges','Interlocks','Alternation'],['DEMAND','STOP','FAULT_A','FAULT_B'],['PUMP_A','PUMP_B']],
 ['Konveyör · sıkışma gözetimi',4,'Çalışan bantta fotosel uzun süre kapalı kalırsa ürün sıkışmış olabilir. Süre dolunca kilitli alarm üret.',['START ile CONVEYOR mühürlensin; STOP ve OVERLOAD hareketi kessin.','RUN sırasında SENSOR kesintisiz {delay} ms aktif kalırsa ALARM kalıcı yansın ve CONVEYOR aynı scan içinde dursun.','SENSOR temizlenince alarm kendiliğinden silinmesin. RESET yalnızca SENSOR FALSE iken alarmı temizlesin.','Alarm resetinden sonra yeni START gereksin.'],['Timers','Diagnostics','Seal-in'],['START','STOP','RESET','OVERLOAD','SENSOR'],['CONVEYOR','ALARM']],
 ['Motor · kontaktör geri bildirim gözetimi',4,'Motor komutu verildiğinde yardımcı kontaktan FEEDBACK beklenir. Çekmeyen kontaktörü veya kaybolan geri bildirimi algıla.',['START ile MOTOR çalışsın; STOP veya OVERLOAD durdursun.','RUN aktifken FEEDBACK kesintisiz {delay} ms gelmezse ALARM kalıcı yansın ve MOTOR dursun.','Geri bildirim zamanında gelirse alarm oluşmasın; çalışma sırasında kaybolması aynı süreyle denetlensin.','RESET yalnızca START bırakılmışken alarmı temizlesin. Yeni START olmadan yeniden çalışma olmasın.'],['Timers','Diagnostics','Interlocks'],['START','STOP','RESET','OVERLOAD','FEEDBACK'],['MOTOR','ALARM']],
 ['4–20 mA · ölçekleme ve sensör teşhisi',4,'Mühendislik birimindeki CURRENT akımını 0–100% seviyeye çevir. Modülün WIRE_BREAK teşhisini ve ölçüm aralığını kontrol et.',['4 mA → %0, 12 mA → %50, 20 mA → %100 olacak şekilde LEVEL hesapla.','CURRENT 4–20 mA aralığındaysa ve WIRE_BREAK FALSE ise VALID aktif olsun.','Aralık dışında veya WIRE_BREAK TRUE olduğunda ALARM yansın; LEVEL son geçerli değerini korusun.','Bu alıştırmada CURRENT doğrudan mA cinsindedir; fiziksel analog modül ham kodlaması kullanılmaz.'],['Analog','Diagnostics'],['WIRE_BREAK'],['VALID','ALARM']]
);
export const catalog=definitions.map((d,i)=>({id:i+1,title:d[0],level:d[1],concepts:d[4]}));
export function challenge(id:number,seed=0):Challenge{
 if(!Number.isInteger(id)||id<1||id>definitions.length||!Number.isInteger(seed)||seed<0||seed>999999)throw Error('Challenge/seed geçersiz');
 const [title,level,scenario,rules,concepts,ins,outs]=definitions[id-1];const delay=(id===22?5000:id===23?8000:1000)+(seed%3)*500,preset=3+(seed%4);
 const tags:Tag[]=[...ins.map((name,i)=>({name,type:'BOOL' as const,address:`%I${Math.floor(i/8)}.${i%8}`,initial:false,inputMode:(['START','STOP','RESET'].includes(name)?'momentary':'toggle') as 'momentary'|'toggle',comment:'Dijital giriş — TRUE: aktif'})),...outs.map((name,i)=>({name,type:'BOOL' as const,address:`%Q0.${i}`,initial:false,comment:'Dijital çıkış'}))];
 ['RUN','SEQ','WAIT_DONE','CYCLE_DONE','TRIGGER','T1_Q','T2_Q','T3_Q'].forEach((name,i)=>tags.push({name,type:'BOOL',address:`%M0.${i}`,initial:false,comment:'Program belleği'}));
 tags.push({name:'RAW',type:'INT',address:'%IW64',initial:0,comment:'Simüle analog modül · 0–27648'},{name:'TEMP',type:'REAL',address:'%MD20',initial:0,comment:'Ölçeklenmiş değer (°C)'});
 if(id>=21&&id<=23)tags.push({name:'LEVEL',type:'REAL',address:'%ID68',initial:0,comment:'Proses seviyesi (%)'},{name:'PROCESS_TEMP',type:'REAL',address:'%ID72',initial:20,comment:'Proses sıcaklığı (°C)'});
 if(id===27)tags.push({name:'CURRENT',type:'REAL',address:'%ID76',initial:4,comment:'Akım (mA), eğitim değeri'},{name:'LEVEL',type:'REAL',address:'%MD24',initial:0,comment:'Geçerli seviye (%)'});
 return {id,seed,title,level,scenario,objectives:rules.map(r=>r.replaceAll('{delay}',String(delay)).replaceAll('{preset}',String(preset))),concepts,tags,delay,preset,plant:id===21?'water':id===22?'mixer':id===23?'roaster':[11,12,20,25].includes(id)?'conveyor':[14,15,17,18].includes(id)?'tank':'motor',hints:[concepts.includes('Seal-in')?'Başlatma butonu bırakıldıktan sonra çalışma bilgisini hangi eleman koruyabilir?':concepts.includes('Timers')?'Çıkış girişle hemen mi değişmeli, yoksa geçen zamana mı bağlı?':concepts.includes('Analog')?'Ham aralığın hangi oranı, mühendislik aralığındaki aynı orana karşılık gelir?':'Her çıkış için izin veren ve engelleyen koşulları ayrı ayrı yaz.',concepts.includes('Seal-in')?'Paralel yollar, başlatma koşulu kalktığında başka bir koşulun iletimi sürdürmesine yardımcı olabilir. Durdurma önceliğini ayrıca değerlendir.':concepts.includes('Timers')?'TON sürekli TRUE süresini, TOF düşen kenardan sonraki süreyi, TP sabit darbeyi temsil eder. Reset koşulunu da incele.':concepts.includes('Analog')?'Önce RAW / 27648.0 oranını bul; sonra 150.0 ile çarp.':'AND bütün izinleri; OR alternatif yolları; NC engelleyici koşulun tersini ifade eder.', 'Sonraki adım düğmesi referans programın yalnızca bir network’ünü yükler. Ardından yeniden test et.']};
}
export function emptyProgram(c:Challenge):Program{return {version:1,cpu:'CPU 1214C DC/DC/DC',tags:c.tags,blocks:[{id:'OB1',kind:'OB',networks:[]},{id:'OB100',kind:'OB',networks:[]}]};}
