// Server-only references and private test sequences. Never import this file in a client component.
import type {Expr,Value,Network,Program,Scalar} from '../plc/model';
import {challenge,emptyProgram,type Challenge} from './catalog';
export interface Step {at:number;inputs?:Record<string,Scalar>;expect:Record<string,Scalar>;reason:string}
export interface Suite {name:string;category:'logic'|'safety';steps:Step[]}
export interface PrivateChallenge {public:Challenge;reference:Program;suites:Suite[]}
export function material(id:number,seed=0):PrivateChallenge {
 const c=challenge(id,seed),p=emptyProgram(c);let seq=0;const key=()=>`ref-${id}-${++seq}`;
 const no=(tag:string):Expr=>({id:key(),type:'NO',tag}),nc=(tag:string):Expr=>({id:key(),type:'NC',tag});
 const and=(...children:Expr[]):Expr=>({id:key(),type:'AND',children}),or=(...children:Expr[]):Expr=>({id:key(),type:'OR',children});
 const lit=(value:number):Value=>({kind:'literal',value}),v=(tag:string):Value=>({kind:'tag',tag});
 const cmp=(tag:string,op:'<'|'>'|'=='|'>='|'<='|'<>',n:number):Expr=>({id:key(),type:'COMPARE',op,a:v(tag),b:lit(n)});
 const timer=(type:'TON'|'TOF'|'TP',input:Expr,pt=c.delay):Expr=>({id:key(),type,input,pt});
 const rung=(title:string,logic:Expr,tag:string,type:'COIL'|'SET'|'RESET'|'MOVE'='COIL',value?:Value)=>p.blocks[0].networks.push({id:key(),title,logic,output:{tag,type,...(value?{value}:{})}});
 const seal=(out:string,stop='STOP',fault='OVERLOAD')=>rung(`${out}: durdurma öncelikli mühürleme`,and(nc(stop),nc(fault),or(no('START'),no(out))),out);
 const run=()=>seal('RUN');
 const suites:Suite[]=[];const test=(name:string,steps:Step[],category:'logic'|'safety'='logic')=>suites.push({name,steps,category});
 const step=(at:number,inputs:Record<string,Scalar>,expect:Record<string,Scalar>,reason:string):Step=>({at,inputs,expect,reason});
 const basicSeal=(out:string,stop='STOP',fault='OVERLOAD')=>{
 test('Start Motor',[step(0,{}, {[out]:false},'Başlangıçta komut olmadan çıkış çalışmamalı.'),step(100,{START:true},{[out]:true},'START çalışma iznini başlatmalı.')]);
 test('Seal-in',[step(0,{START:true},{[out]:true},'Başlatma'),step(100,{START:false},{[out]:true},'START bırakıldığında çıkış FALSE oluyor. Motorun durumunu koruyan paralel yolu incele.')]);
 test('Stop',[step(0,{START:true},{[out]:true},'Başlatma'),step(100,{[stop]:true},{[out]:false},'STOP, START ile birlikte olsa da baskın olmalı.')],'safety');
 test('Overload Trip',[step(0,{START:true},{[out]:true},'Başlatma'),step(100,{START:false,[fault]:true},{[out]:false},'Arıza mühürleme yolunu kesmeli.'),step(200,{[fault]:false},{[out]:false},'Arıza kalkınca START olmadan motor yeniden çalışmamalı.')],'safety');
 test('Start Under Overload',[step(0,{START:true,[fault]:true},{[out]:false},'Aktif arıza altında START çıkışı başlatmamalı.')],'safety');};
 switch(id){
 case 1:case 2:{const b=id===1?'ENABLE':'REMOTE';rung('Buton lojik koşulu',id===1?and(no('START'),no(b)):or(no('START'),no(b)),'MOTOR');for(let a=0;a<2;a++)for(let z=0;z<2;z++)test(`Giriş kombinasyonu ${a}${z}`,[step(0,{START:!!a,[b]:!!z},{MOTOR:id===1?!!(a&&z):!!(a||z)},'Seri/paralel bağlantının doğruluk tablosunu incele.')]);break;}
 case 3:case 4:seal('MOTOR');basicSeal('MOTOR');break;
 case 5:seal('MOTOR','STOP','E_STOP');basicSeal('MOTOR','STOP','E_STOP');break;
 case 6:{rung('İleri kontaktör kilidi',and(nc('STOP'),nc('REVERSE'),or(nc('FWD_CMD'),nc('REV_CMD')),or(and(no('FWD_CMD'),nc('REV_CMD')),no('FORWARD'))),'FORWARD');rung('Geri kontaktör kilidi',and(nc('STOP'),nc('FORWARD'),or(nc('FWD_CMD'),nc('REV_CMD')),or(and(no('REV_CMD'),nc('FWD_CMD')),no('REVERSE'))),'REVERSE');for(const dir of ['FWD','REV']){const out=dir==='FWD'?'FORWARD':'REVERSE',other=dir==='FWD'?'REVERSE':'FORWARD';test(`${dir} başlat ve koru`,[step(0,{[dir+'_CMD']:true},{[out]:true,[other]:false},'Seçilen yön çalışmalı.'),step(100,{[dir+'_CMD']:false},{[out]:true},'Yön mühürlenmeli.'),step(200,{STOP:true},{FORWARD:false,REVERSE:false},'STOP iki yönü durdurmalı.')]);}test('Çalışırken karşı yön kilidi',[step(0,{FWD_CMD:true},{FORWARD:true,REVERSE:false},'İleri başlat'),step(100,{FWD_CMD:false,REV_CMD:true},{FORWARD:true,REVERSE:false},'Çalışan yönden karşı yöne STOP olmadan geçilmemeli.')],'safety');test('Karşıt komutlar',[step(0,{FWD_CMD:true,REV_CMD:true},{FORWARD:false,REVERSE:false},'İki yön komutu birlikte kabul edilmemeli.')],'safety');break;}
 case 7:rung('Kesintisiz başlatma gecikmesi',timer('TON',and(no('START'),nc('OVERLOAD'))),'MOTOR');test('TON sınırları',[step(0,{START:true},{MOTOR:false},'TON hemen aktif olmaz.'),step(c.delay-10,{}, {MOTOR:false},'PT dolmadan çıkış açılmamalı.'),step(c.delay,{}, {MOTOR:true},'Kesintisiz PT sonunda Q aktif olmalı.'),step(c.delay+100,{START:false},{MOTOR:false},'TON giriş kaybında sıfırlanmalı.'),step(c.delay+200,{START:true},{MOTOR:false},'Yeniden başlatmada eski ET kullanılmamalı.')]);test('Arıza timer reset',[step(0,{START:true,OVERLOAD:true},{MOTOR:false},'Arıza altında zamanlama başlamamalı.'),step(c.delay+100,{}, {MOTOR:false},'Arıza altında çıkış kapalı kalmalı.')],'safety');break;
 case 8:rung('Fan kapanma gecikmesi',timer('TOF',no('START')),'FAN');test('TOF düşen kenar',[step(0,{START:true},{FAN:true},'TOF girişi TRUE iken Q hemen TRUE olmalı.'),step(100,{START:false},{FAN:true},'Fan gecikme boyunca açık kalmalı.'),step(100+c.delay-10,{}, {FAN:true},'PT dolmadan kapanmamalı.'),step(100+c.delay,{}, {FAN:false},'PT sonunda fan kapanmalı.')]);test('Yeniden komut',[step(0,{START:true},{FAN:true},'Başlat'),step(100,{START:false},{FAN:true},'Bekle'),step(300,{START:true},{FAN:true},'Yeniden komut gecikmeyi iptal etmeli.'),step(c.delay+200,{}, {FAN:true},'Giriş TRUE iken kapanmamalı.')]);break;
 case 9:rung('Sabit süreli valf darbesi',timer('TP',no('START')),'VALVE');test('Kısa giriş tam darbe',[step(0,{START:true},{VALVE:true},'Yükselen kenar darbeyi başlatmalı.'),step(100,{START:false},{VALVE:true},'TP kısa girişe rağmen darbeyi tamamlamalı.'),step(c.delay,{}, {VALVE:false},'Darbe süresi sonunda kapanmalı.')]);test('Takılı START',[step(0,{START:true},{VALVE:true},'İlk kenar'),step(c.delay,{}, {VALVE:false},'Darbe tamamlandı.'),step(c.delay*2,{}, {VALVE:false},'Sürekli TRUE yeni kenar değildir.')]);break;
 case 10:{rung('Ürün yükselen kenar sayacı',{id:key(),type:'CTU',pv:c.preset,input:no('SENSOR'),reset:no('RESET')},'DONE');const steps:Step[]=[];for(let i=0;i<c.preset;i++){steps.push(step(i*200,{SENSOR:true},{DONE:i===c.preset-1},'CTU sadece yükselen kenarı saymalı.'));steps.push(step(i*200+100,{SENSOR:false},{DONE:i===c.preset-1},'Düşen kenar sayımı değiştirmemeli.'));}steps.push(step(c.preset*200,{RESET:true},{DONE:false},'RESET sayacı temizlemeli.'));test('Sayım ve reset',steps);test('Takılı sensör',[step(0,{SENSOR:true},{DONE:false},'İlk ürün'),step(2000,{}, {DONE:false},'Sürekli TRUE her scan için sayılmamalı.')]);break;}
 case 11:run();rung('Sensör bandı geçici durdurur',and(no('RUN'),nc('SENSOR')),'CONVEYOR');test('Sensör kontrolü',[step(0,{START:true},{CONVEYOR:true},'Başlat'),step(100,{START:false,SENSOR:true},{CONVEYOR:false},'Üründe dur'),step(200,{SENSOR:false},{CONVEYOR:true},'Sensör temizlenince devam et'),step(300,{OVERLOAD:true},{CONVEYOR:false},'Arıza bütün hareketi kesmeli.')],'safety');break;
 case 12:run();rung('Ürünün yalnızca yükselen kenarı',{id:key(),type:'R_TRIG',input:no('SENSOR')},'TRIGGER');rung('Çevrim hafızası',and(no('RUN'),nc('CYCLE_DONE'),or(no('TRIGGER'),no('SEQ'))),'SEQ');rung('İtici öncesi bekleme',timer('TON',no('SEQ')),'WAIT_DONE');rung('500 ms itici süresi',timer('TON',no('WAIT_DONE'),500),'CYCLE_DONE');rung('İtici pencere koşulu',and(no('RUN'),no('WAIT_DONE'),nc('CYCLE_DONE')),'PUSHER');rung('Çevrim dışında bant hareketi',and(no('RUN'),nc('SEQ')),'CONVEYOR');test('Conveyor → wait → pusher → restart',[step(0,{START:true},{CONVEYOR:true,PUSHER:false},'START bandı çalıştırmalı.'),step(100,{START:false,SENSOR:true},{CONVEYOR:false,PUSHER:false},'Sensör algılandığı scan’de bant durmalı.'),step(100+c.delay-10,{}, {PUSHER:false},'İtici gecikmeden önce çalışmamalı.'),step(100+c.delay,{}, {PUSHER:true,CONVEYOR:false},'Bekleme sonunda itici açılmalı.'),step(100+c.delay+490,{}, {PUSHER:true},'İtici tam 500 ms aktif kalmalı.'),step(100+c.delay+500,{}, {PUSHER:false},'500 ms sonunda itici kapanmalı.'),step(100+c.delay+520,{}, {CONVEYOR:true,PUSHER:false},'Bant devam etmeli; sensör takılıysa tekrar darbe olmamalı.'),step(200+c.delay*3,{}, {CONVEYOR:true,PUSHER:false},'Takılı sensör yeni çevrim başlatmamalı.')]);test('İtici sırasında overload',[step(0,{START:true},{CONVEYOR:true},'Başlat'),step(100,{SENSOR:true},{CONVEYOR:false},'Algıla'),step(100+c.delay,{}, {PUSHER:true},'İtici'),step(110+c.delay,{OVERLOAD:true,START:false},{PUSHER:false,CONVEYOR:false},'Arıza beklemeden bütün hareketi kesmeli.')],'safety');break;
 case 13:rung('Çevrim çalışma izni',and(nc('STOP'),or(no('START'),no('RUN'))),'RUN');rung('Yeşil zaman aralığı',timer('TON',and(no('RUN'),nc('T3_Q'))),'T1_Q');rung('Sarı zaman aralığı',timer('TON',and(no('RUN'),no('T1_Q'))),'T2_Q');rung('Kırmızı zaman aralığı',timer('TON',and(no('RUN'),no('T2_Q'))),'T3_Q');rung('Yeşil',and(no('RUN'),nc('T1_Q')),'GREEN');rung('Sarı',and(no('RUN'),no('T1_Q'),nc('T2_Q')),'AMBER');rung('Kırmızı',and(no('RUN'),no('T2_Q')),'RED');test('Üç faz ve tekrar',[step(0,{START:true},{GREEN:true,AMBER:false,RED:false},'İlk faz yeşil'),step(c.delay,{START:false},{GREEN:false,AMBER:true,RED:false},'İkinci faz sarı'),step(c.delay*2,{}, {GREEN:false,AMBER:false,RED:true},'Üçüncü faz kırmızı'),step(c.delay*3+20,{}, {GREEN:true,AMBER:false,RED:false},'Çevrim tekrar başlamalı'),step(c.delay*3+100,{STOP:true},{GREEN:false,AMBER:false,RED:false},'STOP bütün lambaları kesmeli')]);break;
 case 14:case 15:{const begin=id===14?'LOW':'HIGH',end=id===14?'HIGH':'EMPTY',out=id===14?'VALVE':'PUMP';rung('Seviye aralığı hafızası',and(nc(end),nc('FAULT'),or(no(begin),no(out))),out);test('Seviye histerezisi',[step(0,{[begin]:true},{[out]:true},'Başlangıç seviyesi'),step(100,{[begin]:false},{[out]:true},'Ara seviyede durum korunmalı.'),step(200,{[end]:true},{[out]:false},'Bitiş seviyesinde durmalı.')]);test('Sensör/arıza önceliği',[step(0,{[begin]:true,[end]:true},{[out]:false},'Çelişen şalterlerde durdurma öncelikli.'),step(100,{[end]:false,FAULT:true},{[out]:false},'Arızada kapalı kalmalı.')],'safety');break;}
 case 16:rung('Su izniyle mühürleme',and(nc('STOP'),no('WATER_OK'),or(no('START'),no('PUMP'))),'PUMP');test('Kuru çalışma koruması',[step(0,{START:true},{PUMP:false},'Su yokken başlatma yasak.'),step(100,{WATER_OK:true},{PUMP:true},'Su izni ve START'),step(200,{START:false},{PUMP:true},'Mühürleme'),step(300,{WATER_OK:false},{PUMP:false},'Su kaybında dur.'),step(400,{WATER_OK:true},{PUMP:false},'Su gelince otomatik başlama.')],'safety');break;
 case 17:case 18:{const scale:Value={kind:'calc',op:'MUL',a:{kind:'calc',op:'DIV',a:v('RAW'),b:lit(27648)},b:lit(150)};rung('Ham değerden °C ölçekleme',cmp('RAW','>=',-32768),'TEMP','MOVE',scale);if(id===17){rung('Alt eşikte ısıtıcıyı set et',and(nc('FAULT'),cmp('RAW','>=',0),cmp('RAW','<=',27648),cmp('TEMP','<',70)),'HEATER','SET');rung('Üst eşik ve sensör arızası',or(no('FAULT'),cmp('RAW','<',0),cmp('RAW','>',27648),cmp('TEMP','>',75)),'HEATER','RESET');test('Histerezis',[step(0,{RAW:12000},{HEATER:true},'Düşük sıcaklıkta ısıt.'),step(100,{RAW:13271},{HEATER:true},'72 °C: önceki ON korunmalı.'),step(200,{RAW:15000},{HEATER:false},'75 °C üstünde kapat.'),step(300,{RAW:13271},{HEATER:false},'72 °C: önceki OFF korunmalı.')]);test('Sensör arızası',[step(0,{RAW:10000,FAULT:true},{HEATER:false},'FAULT ısıtmayı engellemeli.'),step(100,{FAULT:false,RAW:30000},{HEATER:false},'Ham aralık dışı güvenli kapatma.'),step(200,{RAW:-1},{HEATER:false},'Negatif ham değer güvenli kapatma.')],'safety');}for(const raw of[0,6912,13824,18432,27648])test(`Ölçek ${raw}`,[step(0,{RAW:raw},{TEMP:raw/27648*150},'RAW / 27648 × 150 oranını REAL olarak hesapla.')]);break;}
 case 19:seal('MOTOR');rung('Yıldız süresi',timer('TON',no('MOTOR')),'T1_Q');rung('Açık geçiş',timer('TON',and(no('MOTOR'),no('T1_Q')),100),'T2_Q');rung('Yıldız kontaktörü',and(no('MOTOR'),nc('T1_Q')),'STAR');rung('Üçgen kontaktörü',and(no('MOTOR'),no('T2_Q')),'DELTA');test('Açık geçişli yıldız üçgen',[step(0,{START:true},{MOTOR:true,STAR:true,DELTA:false},'Yıldız başlangıç'),step(c.delay,{START:false},{STAR:false,DELTA:false},'100 ms açık geçiş'),step(c.delay+90,{}, {STAR:false,DELTA:false},'Geçiş tamamlanmadı'),step(c.delay+100,{}, {STAR:false,DELTA:true},'Üçgen çalışma'),step(c.delay+200,{OVERLOAD:true},{MOTOR:false,STAR:false,DELTA:false},'Arıza bütün kontaktörleri kesmeli.')],'safety');break;
 case 20:run();rung('Büyük ürün ayırma',and(no('RUN'),no('SENSOR'),no('LARGE')),'PUSHER');rung('Ayırma dışında hareket',and(no('RUN'),or(nc('SENSOR'),nc('LARGE'))),'CONVEYOR');test('Boyuta göre ayırma',[step(0,{START:true},{CONVEYOR:true,PUSHER:false},'Başlat'),step(100,{START:false,SENSOR:true,LARGE:false},{CONVEYOR:true,PUSHER:false},'Küçük ürünü geçir'),step(200,{LARGE:true},{CONVEYOR:false,PUSHER:true},'Büyük ürünü ayır'),step(300,{SENSOR:false},{CONVEYOR:true,PUSHER:false},'Sonraki ürüne devam'),step(400,{OVERLOAD:true},{CONVEYOR:false,PUSHER:false},'Arızada güvenli duruş')],'safety');break;
 }
 return {public:c,reference:p,suites};
}

