// Server-only references and private test sequences. Never import this file in a client component.
// Language: material(id,seed,lang) builds the reference program and its suites in one language. Reasons, suite titles
// and network titles are written side by side as (en,tr) pairs and picked once, so titles never influence the logic.
// Suite.name is the STABLE, language-independent key (English); Suite.title is the localized display name.
import type {Expr,Value,Network,Program,Scalar} from '../plc/model';
import {pick,type Lang} from '../i18n/core';
import {challenge,emptyProgram,type Challenge} from './catalog';
export interface Step {at:number;inputs?:Record<string,Scalar>;expect:Record<string,Scalar>;reason:string}
export interface Suite {name:string;title:string;category:'logic'|'safety';steps:Step[]}
export interface PrivateChallenge {public:Challenge;reference:Program;suites:Suite[]}
export function material(id:number,seed=0,lang:Lang='en'):PrivateChallenge {
 const c=challenge(id,seed,lang),p=emptyProgram(c);let seq=0;const key=()=>`ref-${id}-${++seq}`;
 const t=(en:string,tr:string)=>pick({en,tr},lang);
 const no=(tag:string):Expr=>({id:key(),type:'NO',tag}),nc=(tag:string):Expr=>({id:key(),type:'NC',tag});
 const and=(...children:Expr[]):Expr=>({id:key(),type:'AND',children}),or=(...children:Expr[]):Expr=>({id:key(),type:'OR',children});
 const lit=(value:number):Value=>({kind:'literal',value}),v=(tag:string):Value=>({kind:'tag',tag});
 const cmp=(tag:string,op:'<'|'>'|'=='|'>='|'<='|'<>',n:number):Expr=>({id:key(),type:'COMPARE',op,a:v(tag),b:lit(n)});
 const timer=(type:'TON'|'TOF'|'TP',input:Expr,pt=c.delay):Expr=>({id:key(),type,input,pt});
 const rung=(en:string,tr:string,logic:Expr,tag:string,type:'COIL'|'SET'|'RESET'|'MOVE'='COIL',value?:Value)=>p.blocks[0].networks.push({id:key(),title:t(en,tr),logic,output:{tag,type,...(value?{value}:{})}});
 const seal=(out:string,stop='STOP',fault='OVERLOAD')=>rung(`${out}: stop-dominant seal-in`,`${out}: durdurma öncelikli mühürleme`,and(nc(stop),nc(fault),or(no('START'),no(out))),out);
 const run=()=>seal('RUN');
 const suites:Suite[]=[];
 // name: stable English key; tr: Turkish display title (the English display title is the name itself).
 const test=(name:string,tr:string,steps:Step[],category:'logic'|'safety'='logic')=>suites.push({name,title:t(name,tr),steps,category});
 const step=(at:number,inputs:Record<string,Scalar>,expect:Record<string,Scalar>,en:string,tr:string):Step=>({at,inputs,expect,reason:t(en,tr)});
 const basicSeal=(out:string,stop='STOP',fault='OVERLOAD')=>{
 test('Start Motor','Motoru başlat',[step(0,{}, {[out]:false},'With no command the output must stay off at start-up.','Başlangıçta komut olmadan çıkış çalışmamalı.'),step(100,{START:true},{[out]:true},'START must start the output.','START çalışma iznini başlatmalı.')]);
 test('Seal-in','Mühürleme',[step(0,{START:true},{[out]:true},'Start','Başlatma'),step(100,{START:false},{[out]:true},'The output goes FALSE when START is released. Look at the parallel branch that holds the motor state.','START bırakıldığında çıkış FALSE oluyor. Motorun durumunu koruyan paralel yolu incele.')]);
 test('Stop','Durdurma',[step(0,{START:true},{[out]:true},'Start','Başlatma'),step(100,{[stop]:true},{[out]:false},'STOP must take priority even when START is held at the same time.','STOP, START ile birlikte olsa da baskın olmalı.')],'safety');
 test('Overload Trip','Aşırı yük arızası',[step(0,{START:true},{[out]:true},'Start','Başlatma'),step(100,{START:false,[fault]:true},{[out]:false},'The fault must break the seal-in path.','Arıza mühürleme yolunu kesmeli.'),step(200,{[fault]:false},{[out]:false},'When the fault clears, the motor must not restart without a new START.','Arıza kalkınca START olmadan motor yeniden çalışmamalı.')],'safety');
 test('Start Under Overload','Arıza altında başlatma',[step(0,{START:true,[fault]:true},{[out]:false},'START must not start the output while a fault is active.','Aktif arıza altında START çıkışı başlatmamalı.')],'safety');};
 switch(id){
 case 1:case 2:{const b=id===1?'ENABLE':'REMOTE';rung('Pushbutton logic condition','Buton lojik koşulu',id===1?and(no('START'),no(b)):or(no('START'),no(b)),'MOTOR');for(let a=0;a<2;a++)for(let z=0;z<2;z++)test(`Input combination ${a}${z}`,`Giriş kombinasyonu ${a}${z}`,[step(0,{START:!!a,[b]:!!z},{MOTOR:id===1?!!(a&&z):!!(a||z)},'Check the truth table of the series/parallel connection.','Seri/paralel bağlantının doğruluk tablosunu incele.')]);break;}
 case 3:case 4:seal('MOTOR');basicSeal('MOTOR');break;
 case 5:seal('MOTOR','STOP','E_STOP');basicSeal('MOTOR','STOP','E_STOP');break;
 case 6:{rung('Forward contactor interlock','İleri kontaktör kilidi',and(nc('STOP'),nc('REVERSE'),or(nc('FWD_CMD'),nc('REV_CMD')),or(and(no('FWD_CMD'),nc('REV_CMD')),no('FORWARD'))),'FORWARD');rung('Reverse contactor interlock','Geri kontaktör kilidi',and(nc('STOP'),nc('FORWARD'),or(nc('FWD_CMD'),nc('REV_CMD')),or(and(no('REV_CMD'),nc('FWD_CMD')),no('REVERSE'))),'REVERSE');for(const dir of ['FWD','REV']){const out=dir==='FWD'?'FORWARD':'REVERSE',other=dir==='FWD'?'REVERSE':'FORWARD';test(`${dir} start and hold`,`${dir} başlat ve koru`,[step(0,{[dir+'_CMD']:true},{[out]:true,[other]:false},'The selected direction must run.','Seçilen yön çalışmalı.'),step(100,{[dir+'_CMD']:false},{[out]:true},'The direction must be sealed in.','Yön mühürlenmeli.'),step(200,{STOP:true},{FORWARD:false,REVERSE:false},'STOP must stop both directions.','STOP iki yönü durdurmalı.')]);}test('Opposite direction locked while running','Çalışırken karşı yön kilidi',[step(0,{FWD_CMD:true},{FORWARD:true,REVERSE:false},'Start forward','İleri başlat'),step(100,{FWD_CMD:false,REV_CMD:true},{FORWARD:true,REVERSE:false},'The running direction must not change to the opposite one without STOP.','Çalışan yönden karşı yöne STOP olmadan geçilmemeli.')],'safety');test('Conflicting commands','Karşıt komutlar',[step(0,{FWD_CMD:true,REV_CMD:true},{FORWARD:false,REVERSE:false},'Both direction commands together must not be accepted.','İki yön komutu birlikte kabul edilmemeli.')],'safety');break;}
 case 7:rung('Uninterrupted start delay','Kesintisiz başlatma gecikmesi',timer('TON',and(no('START'),nc('OVERLOAD'))),'MOTOR');test('TON limits','TON sınırları',[step(0,{START:true},{MOTOR:false},'TON does not become active immediately.','TON hemen aktif olmaz.'),step(c.delay-10,{}, {MOTOR:false},'The output must not turn on before PT has elapsed.','PT dolmadan çıkış açılmamalı.'),step(c.delay,{}, {MOTOR:true},'Q must be active once PT has elapsed without interruption.','Kesintisiz PT sonunda Q aktif olmalı.'),step(c.delay+100,{START:false},{MOTOR:false},'TON must reset when the input is lost.','TON giriş kaybında sıfırlanmalı.'),step(c.delay+200,{START:true},{MOTOR:false},'A restart must not reuse the old ET.','Yeniden başlatmada eski ET kullanılmamalı.')]);test('Timer reset on fault','Arıza timer reset',[step(0,{START:true,OVERLOAD:true},{MOTOR:false},'Timing must not start while a fault is active.','Arıza altında zamanlama başlamamalı.'),step(c.delay+100,{}, {MOTOR:false},'The output must stay off while the fault is active.','Arıza altında çıkış kapalı kalmalı.')],'safety');break;
 case 8:rung('Fan off-delay','Fan kapanma gecikmesi',timer('TOF',no('START')),'FAN');test('TOF falling edge','TOF düşen kenar',[step(0,{START:true},{FAN:true},'While the TOF input is TRUE, Q must be TRUE immediately.','TOF girişi TRUE iken Q hemen TRUE olmalı.'),step(100,{START:false},{FAN:true},'The fan must stay on during the delay.','Fan gecikme boyunca açık kalmalı.'),step(100+c.delay-10,{}, {FAN:true},'It must not switch off before PT has elapsed.','PT dolmadan kapanmamalı.'),step(100+c.delay,{}, {FAN:false},'The fan must switch off when PT has elapsed.','PT sonunda fan kapanmalı.')]);test('Re-command','Yeniden komut',[step(0,{START:true},{FAN:true},'Start','Başlat'),step(100,{START:false},{FAN:true},'Wait','Bekle'),step(300,{START:true},{FAN:true},'A new command must cancel the delay.','Yeniden komut gecikmeyi iptal etmeli.'),step(c.delay+200,{}, {FAN:true},'It must not switch off while the input is TRUE.','Giriş TRUE iken kapanmamalı.')]);break;
 case 9:rung('Fixed-duration valve pulse','Sabit süreli valf darbesi',timer('TP',no('START')),'VALVE');test('Short input, full pulse','Kısa giriş tam darbe',[step(0,{START:true},{VALVE:true},'A rising edge must start the pulse.','Yükselen kenar darbeyi başlatmalı.'),step(100,{START:false},{VALVE:true},'TP must complete the pulse despite the short input.','TP kısa girişe rağmen darbeyi tamamlamalı.'),step(c.delay,{}, {VALVE:false},'It must switch off when the pulse time has elapsed.','Darbe süresi sonunda kapanmalı.')]);test('Stuck START','Takılı START',[step(0,{START:true},{VALVE:true},'First edge','İlk kenar'),step(c.delay,{}, {VALVE:false},'Pulse complete.','Darbe tamamlandı.'),step(c.delay*2,{}, {VALVE:false},'A permanently TRUE input is not a new edge.','Sürekli TRUE yeni kenar değildir.')]);break;
 case 10:{rung('Product rising-edge counter','Ürün yükselen kenar sayacı',{id:key(),type:'CTU',pv:c.preset,input:no('SENSOR'),reset:no('RESET')},'DONE');const steps:Step[]=[];for(let i=0;i<c.preset;i++){steps.push(step(i*200,{SENSOR:true},{DONE:i===c.preset-1},'CTU must count rising edges only.','CTU sadece yükselen kenarı saymalı.'));steps.push(step(i*200+100,{SENSOR:false},{DONE:i===c.preset-1},'A falling edge must not change the count.','Düşen kenar sayımı değiştirmemeli.'));}steps.push(step(c.preset*200,{RESET:true},{DONE:false},'RESET must clear the counter.','RESET sayacı temizlemeli.'));test('Count and reset','Sayım ve reset',steps);test('Stuck sensor','Takılı sensör',[step(0,{SENSOR:true},{DONE:false},'First product','İlk ürün'),step(2000,{}, {DONE:false},'A permanently TRUE input must not be counted on every scan.','Sürekli TRUE her scan için sayılmamalı.')]);break;}
 case 11:run();rung('Sensor pauses the conveyor','Sensör bandı geçici durdurur',and(no('RUN'),nc('SENSOR')),'CONVEYOR');test('Sensor control','Sensör kontrolü',[step(0,{START:true},{CONVEYOR:true},'Start','Başlat'),step(100,{START:false,SENSOR:true},{CONVEYOR:false},'Stop at the product','Üründe dur'),step(200,{SENSOR:false},{CONVEYOR:true},'Resume when the sensor clears','Sensör temizlenince devam et'),step(300,{OVERLOAD:true},{CONVEYOR:false},'A fault must cut all motion.','Arıza bütün hareketi kesmeli.')],'safety');break;
 case 12:run();rung('Rising edge of the product only','Ürünün yalnızca yükselen kenarı',{id:key(),type:'R_TRIG',input:no('SENSOR')},'TRIGGER');rung('Cycle memory','Çevrim hafızası',and(no('RUN'),nc('CYCLE_DONE'),or(no('TRIGGER'),no('SEQ'))),'SEQ');rung('Wait before the pusher','İtici öncesi bekleme',timer('TON',no('SEQ')),'WAIT_DONE');rung('500 ms pusher time','500 ms itici süresi',timer('TON',no('WAIT_DONE'),500),'CYCLE_DONE');rung('Pusher window condition','İtici pencere koşulu',and(no('RUN'),no('WAIT_DONE'),nc('CYCLE_DONE')),'PUSHER');rung('Conveyor motion outside the cycle','Çevrim dışında bant hareketi',and(no('RUN'),nc('SEQ')),'CONVEYOR');test('Conveyor → wait → pusher → restart','Bant → bekleme → itici → yeniden başlama',[step(0,{START:true},{CONVEYOR:true,PUSHER:false},'START must run the conveyor.','START bandı çalıştırmalı.'),step(100,{START:false,SENSOR:true},{CONVEYOR:false,PUSHER:false},'The conveyor must stop in the scan in which the sensor is detected.','Sensör algılandığı scan’de bant durmalı.'),step(100+c.delay-10,{}, {PUSHER:false},'The pusher must not run before the delay.','İtici gecikmeden önce çalışmamalı.'),step(100+c.delay,{}, {PUSHER:true,CONVEYOR:false},'The pusher must open when the wait ends.','Bekleme sonunda itici açılmalı.'),step(100+c.delay+490,{}, {PUSHER:true},'The pusher must stay active for exactly 500 ms.','İtici tam 500 ms aktif kalmalı.'),step(100+c.delay+500,{}, {PUSHER:false},'The pusher must close after 500 ms.','500 ms sonunda itici kapanmalı.'),step(100+c.delay+520,{}, {CONVEYOR:true,PUSHER:false},'The conveyor must resume; if the sensor is stuck, there must be no second pulse.','Bant devam etmeli; sensör takılıysa tekrar darbe olmamalı.'),step(200+c.delay*3,{}, {CONVEYOR:true,PUSHER:false},'A stuck sensor must not start a new cycle.','Takılı sensör yeni çevrim başlatmamalı.')]);test('Overload during pusher','İtici sırasında overload',[step(0,{START:true},{CONVEYOR:true},'Start','Başlat'),step(100,{SENSOR:true},{CONVEYOR:false},'Detect','Algıla'),step(100+c.delay,{}, {PUSHER:true},'Pusher','İtici'),step(110+c.delay,{OVERLOAD:true,START:false},{PUSHER:false,CONVEYOR:false},'A fault must cut all motion immediately, without waiting.','Arıza beklemeden bütün hareketi kesmeli.')],'safety');break;
 case 13:rung('Cycle run permissive','Çevrim çalışma izni',and(nc('STOP'),or(no('START'),no('RUN'))),'RUN');rung('Green time slot','Yeşil zaman aralığı',timer('TON',and(no('RUN'),nc('T3_Q'))),'T1_Q');rung('Amber time slot','Sarı zaman aralığı',timer('TON',and(no('RUN'),no('T1_Q'))),'T2_Q');rung('Red time slot','Kırmızı zaman aralığı',timer('TON',and(no('RUN'),no('T2_Q'))),'T3_Q');rung('Green','Yeşil',and(no('RUN'),nc('T1_Q')),'GREEN');rung('Amber','Sarı',and(no('RUN'),no('T1_Q'),nc('T2_Q')),'AMBER');rung('Red','Kırmızı',and(no('RUN'),no('T2_Q')),'RED');test('Three phases and repeat','Üç faz ve tekrar',[step(0,{START:true},{GREEN:true,AMBER:false,RED:false},'First phase: green','İlk faz yeşil'),step(c.delay,{START:false},{GREEN:false,AMBER:true,RED:false},'Second phase: amber','İkinci faz sarı'),step(c.delay*2,{}, {GREEN:false,AMBER:false,RED:true},'Third phase: red','Üçüncü faz kırmızı'),step(c.delay*3+20,{}, {GREEN:true,AMBER:false,RED:false},'The cycle must start again','Çevrim tekrar başlamalı'),step(c.delay*3+100,{STOP:true},{GREEN:false,AMBER:false,RED:false},'STOP must switch off all lamps','STOP bütün lambaları kesmeli')]);break;
 case 14:case 15:{const begin=id===14?'LOW':'HIGH',end=id===14?'HIGH':'EMPTY',out=id===14?'VALVE':'PUMP';rung('Level range memory','Seviye aralığı hafızası',and(nc(end),nc('FAULT'),or(no(begin),no(out))),out);test('Level hysteresis','Seviye histerezisi',[step(0,{[begin]:true},{[out]:true},'Start level','Başlangıç seviyesi'),step(100,{[begin]:false},{[out]:true},'The state must be held at the intermediate level.','Ara seviyede durum korunmalı.'),step(200,{[end]:true},{[out]:false},'It must stop at the end level.','Bitiş seviyesinde durmalı.')]);test('Sensor/fault priority','Sensör/arıza önceliği',[step(0,{[begin]:true,[end]:true},{[out]:false},'With contradictory switches, stop must take priority.','Çelişen şalterlerde durdurma öncelikli.'),step(100,{[end]:false,FAULT:true},{[out]:false},'It must stay off during a fault.','Arızada kapalı kalmalı.')],'safety');break;}
 case 16:rung('Seal-in with water permissive','Su izniyle mühürleme',and(nc('STOP'),no('WATER_OK'),or(no('START'),no('PUMP'))),'PUMP');test('Dry-run protection','Kuru çalışma koruması',[step(0,{START:true},{PUMP:false},'Starting without water is forbidden.','Su yokken başlatma yasak.'),step(100,{WATER_OK:true},{PUMP:true},'Water permissive and START','Su izni ve START'),step(200,{START:false},{PUMP:true},'Seal-in','Mühürleme'),step(300,{WATER_OK:false},{PUMP:false},'Stop when water is lost.','Su kaybında dur.'),step(400,{WATER_OK:true},{PUMP:false},'No automatic start when water returns.','Su gelince otomatik başlama.')],'safety');break;
 case 17:case 18:{const scale:Value={kind:'calc',op:'MUL',a:{kind:'calc',op:'DIV',a:v('RAW'),b:lit(27648)},b:lit(150)};rung('Scale the raw value to °C','Ham değerden °C ölçekleme',cmp('RAW','>=',-32768),'TEMP','MOVE',scale);if(id===17){rung('Set the heater at the lower threshold','Alt eşikte ısıtıcıyı set et',and(nc('FAULT'),cmp('RAW','>=',0),cmp('RAW','<=',27648),cmp('TEMP','<',70)),'HEATER','SET');rung('Upper threshold and sensor fault','Üst eşik ve sensör arızası',or(no('FAULT'),cmp('RAW','<',0),cmp('RAW','>',27648),cmp('TEMP','>',75)),'HEATER','RESET');test('Hysteresis','Histerezis',[step(0,{RAW:12000},{HEATER:true},'Heat at a low temperature.','Düşük sıcaklıkta ısıt.'),step(100,{RAW:13271},{HEATER:true},'72 °C: the previous ON state must be held.','72 °C: önceki ON korunmalı.'),step(200,{RAW:15000},{HEATER:false},'Switch off above 75 °C.','75 °C üstünde kapat.'),step(300,{RAW:13271},{HEATER:false},'72 °C: the previous OFF state must be held.','72 °C: önceki OFF korunmalı.')]);test('Sensor fault','Sensör arızası',[step(0,{RAW:10000,FAULT:true},{HEATER:false},'FAULT must inhibit heating.','FAULT ısıtmayı engellemeli.'),step(100,{FAULT:false,RAW:30000},{HEATER:false},'Raw value out of range: safe shut-off.','Ham aralık dışı güvenli kapatma.'),step(200,{RAW:-1},{HEATER:false},'Negative raw value: safe shut-off.','Negatif ham değer güvenli kapatma.')],'safety');}for(const raw of[0,6912,13824,18432,27648])test(`Scale ${raw}`,`Ölçek ${raw}`,[step(0,{RAW:raw},{TEMP:raw/27648*150},'Calculate the ratio RAW / 27648 × 150 as REAL.','RAW / 27648 × 150 oranını REAL olarak hesapla.')]);break;}
 case 19:seal('MOTOR');rung('Star time','Yıldız süresi',timer('TON',no('MOTOR')),'T1_Q');rung('Open transition','Açık geçiş',timer('TON',and(no('MOTOR'),no('T1_Q')),100),'T2_Q');rung('Star contactor','Yıldız kontaktörü',and(no('MOTOR'),nc('T1_Q')),'STAR');rung('Delta contactor','Üçgen kontaktörü',and(no('MOTOR'),no('T2_Q')),'DELTA');test('Open-transition star-delta','Açık geçişli yıldız üçgen',[step(0,{START:true},{MOTOR:true,STAR:true,DELTA:false},'Star start-up','Yıldız başlangıç'),step(c.delay,{START:false},{STAR:false,DELTA:false},'100 ms open transition','100 ms açık geçiş'),step(c.delay+90,{}, {STAR:false,DELTA:false},'Transition not yet complete','Geçiş tamamlanmadı'),step(c.delay+100,{}, {STAR:false,DELTA:true},'Delta run','Üçgen çalışma'),step(c.delay+200,{OVERLOAD:true},{MOTOR:false,STAR:false,DELTA:false},'A fault must cut all contactors.','Arıza bütün kontaktörleri kesmeli.')],'safety');break;
 case 24:{
 rung('Falling edge of the demand','Talep bitiş kenarı',{id:key(),type:'F_TRIG',input:no('DEMAND')},'TRIGGER');
 rung('Previous pump selection','Önceki pompa seçimi',no('SEQ'),'T1_Q');
 rung('Toggle the selection at the end of each demand','Her talep sonunda seçim değiştir',or(and(no('TRIGGER'),nc('T1_Q')),and(nc('TRIGGER'),no('T1_Q'))),'SEQ');
 rung('Pump A when selected, or as standby for a fault on B','A seçimi veya B arızasında yedek',and(no('DEMAND'),nc('STOP'),nc('FAULT_A'),or(nc('SEQ'),no('FAULT_B'))),'PUMP_A');
 rung('Pump B when selected, or as standby for a fault on A','B seçimi veya A arızasında yedek',and(no('DEMAND'),nc('STOP'),nc('FAULT_B'),or(no('SEQ'),no('FAULT_A'))),'PUMP_B');
 test('A → B → A and constant demand','A → B → A ve sabit talep',[step(0,{DEMAND:true},{PUMP_A:true,PUMP_B:false},'First demand: A.','İlk talep A.'),step(200,{}, {PUMP_A:true,PUMP_B:false},'A constant input does not change the selection.','Sabit giriş seçim değiştirmez.'),step(300,{DEMAND:false},{PUMP_A:false,PUMP_B:false},'Demand ended.','Talep bitti.'),step(400,{DEMAND:true},{PUMP_A:false,PUMP_B:true},'Second demand: B.','İkinci talep B.'),step(500,{DEMAND:false},{PUMP_A:false,PUMP_B:false},'Demand ended.','Talep bitti.'),step(600,{DEMAND:true},{PUMP_A:true,PUMP_B:false},'Third demand: A.','Üçüncü talep A.')]);
 test('Standby pump and double fault','Yedek pompa ve iki arıza',[step(0,{DEMAND:true,FAULT_A:true},{PUMP_A:false,PUMP_B:true},'The healthy pump must take over.','Sağlam pompa devralsın.'),step(100,{FAULT_B:true},{PUMP_A:false,PUMP_B:false},'Stop on a double fault.','İki arızada dur.'),step(200,{FAULT_A:false,FAULT_B:false,STOP:true},{PUMP_A:false,PUMP_B:false},'STOP takes priority.','STOP öncelikli.')],'safety');break;}
 case 25:case 26:{
 const jam=id===25,out=jam?'CONVEYOR':'MOTOR';
 rung('The operator resets the alarm','Alarmı operatör resetler',and(no('RESET'),nc(jam?'SENSOR':'START')),'ALARM','RESET');
 rung('Run permissive','Çalışma izni',and(nc('STOP'),nc('OVERLOAD'),nc('ALARM'),or(no('START'),no('RUN'))),'RUN');
 rung('Feedback time','Geri bildirim süresi',timer('TON',and(no('RUN'),jam?no('SENSOR'):nc('FEEDBACK'))),'T1_Q');
 rung('Latch the timeout','Zaman aşımını kilitle',no('T1_Q'),'ALARM','SET');
 rung('Cut the motion in the same scan','Aynı scan içinde hareketi kes',and(no('RUN'),nc('ALARM')),out);
 test('Time limit, latched alarm and reset','Süre sınırı, kilitli alarm ve reset',[step(0,{START:true,...(jam?{SENSOR:true}:{FEEDBACK:false})},{[out]:true,ALARM:false},'Monitoring starts.','İzleme başlar.'),step(c.delay-10,{START:false},{[out]:true,ALARM:false},'No alarm before PT.','PT öncesi alarm yok.'),step(c.delay,{}, {[out]:false,ALARM:true},'Stop exactly at PT.','PT anında dur.'),step(c.delay+100,jam?{SENSOR:false}:{FEEDBACK:true},{[out]:false,ALARM:true},'The alarm must stay latched even if the input recovers.','Giriş düzelse de alarm korunsun.'),step(c.delay+200,{RESET:true},{[out]:false,ALARM:false},'Reset must not start motion.','Reset hareket başlatmaz.'),step(c.delay+300,{RESET:false,START:true},{[out]:true,ALARM:false},'A new START is required.','Yeni START gerekli.')]);
 test('Normal sensor behavior','Normal sensör davranışı',[step(0,{START:true,...(jam?{SENSOR:false}:{FEEDBACK:true})},{[out]:true,ALARM:false},'Normal operation.','Normal çalışma.'),step(c.delay+500,{START:false},{[out]:true,ALARM:false},'Healthy feedback must not raise an alarm.','Sağlıklı geri bildirim alarm üretmez.'),step(c.delay+600,{STOP:true},{[out]:false},'STOP stops the motion.','STOP durdurur.')],'safety');break;}
 case 27:{
 rung('Current range and module diagnostics','Akım aralığı ve modül teşhisi',and(nc('WIRE_BREAK'),cmp('CURRENT','>=',4),cmp('CURRENT','<=',20)),'VALID');
 rung('Sensor alarm','Sensör alarmı',nc('VALID'),'ALARM');
 rung('Scale the valid current to a level','Geçerli akımı seviyeye ölçekle',no('VALID'),'LEVEL','MOVE',{kind:'calc',op:'MUL',a:{kind:'calc',op:'DIV',a:{kind:'calc',op:'SUB',a:v('CURRENT'),b:lit(4)},b:lit(16)},b:lit(100)});
 test('Current scaling','Akım ölçeği',[step(0,{CURRENT:4},{LEVEL:0,VALID:true,ALARM:false},'4 mA is zero.','4 mA sıfır.'),step(100,{CURRENT:12},{LEVEL:50},'12 mA is the midpoint.','12 mA orta nokta.'),step(200,{CURRENT:20},{LEVEL:100},'20 mA is full scale.','20 mA tam skala.')]);
 test('Last valid value and wire break','Son geçerli değer ve kablo kopması',[step(0,{CURRENT:12},{LEVEL:50},'Last valid value.','Son geçerli değer.'),step(100,{CURRENT:2},{LEVEL:50,VALID:false,ALARM:true},'Low current is invalid.','Düşük akım geçersiz.'),step(200,{CURRENT:22},{LEVEL:50,VALID:false,ALARM:true},'High current is invalid.','Yüksek akım geçersiz.'),step(300,{CURRENT:16,WIRE_BREAK:true},{LEVEL:50,VALID:false,ALARM:true},'Module diagnostics take priority.','Modül teşhisi baskın.'),step(400,{WIRE_BREAK:false},{LEVEL:75,VALID:true,ALARM:false},'Return to a healthy measurement.','Sağlıklı ölçüme dön.')],'safety');break;}
 case 21:case 22:case 23:{
 const batch=id===21,mix=id===22;
 rung('The operator clears the done flag','Tamamlandı bilgisini operatör sıfırlar',no('RESET'),'DONE','RESET');
 rung('Cycle permissive and restart lock','Çevrim izni ve yeniden başlatma kilidi',and(nc('STOP'),nc('FAULT'),nc('DONE'),...(batch?[]:[no('LID_CLOSED')]),or(no('START'),no('RUN'))),'RUN');
 rung('Hold the next stage in memory','Bir sonraki aşamayı hafızada tut',and(no('RUN'),or(batch?no('HIGH'):mix?and(no('A_READY'),no('B_READY')):no('HOT'),no('SEQ'))),'SEQ');
 if(!batch)rung(mix?'Mixing time':'Roasting time after the target is reached',mix?'Karışım süresi':'Hedefe ulaştıktan sonra kavurma süresi',timer('TON',and(no('RUN'),no('SEQ'))),'WAIT_DONE');
 rung('Batch complete','Parti tamamlandı',and(no('RUN'),no(batch?'SEQ':'WAIT_DONE'),no('EMPTY'),...(id===23?[no('COOL')]:[])),'DONE','SET');
 const enabled=()=>and(no('RUN'),nc('DONE'));
 if(batch){rung('Fill','Dolum',and(enabled(),nc('SEQ'),nc('HIGH')),'VALVE');rung('Transfer pump','Transfer pompası',and(enabled(),no('SEQ'),nc('EMPTY')),'PUMP');}
 else if(mix){for(const [out,ready] of [['DOSE_A','A_READY'],['DOSE_B','B_READY']])rung(out+' dosing',out+' dozajı',and(enabled(),nc('SEQ'),nc(ready)),out);rung('Mixing','Karıştırma',and(enabled(),no('SEQ'),nc('WAIT_DONE')),'MIXER');rung('Drain the product','Ürünü boşalt',and(enabled(),no('WAIT_DONE'),nc('EMPTY')),'DRAIN');}
 else {rung('Turn the drum','Tamburu döndür',enabled(),'DRUM');rung('Heat below the target','Hedef altında ısıt',and(enabled(),nc('WAIT_DONE'),nc('HOT')),'HEATER');rung('Cooling fan','Soğutma fanı',and(enabled(),no('WAIT_DONE'),nc('COOL')),'FAN');rung('Discharge the cooled product','Soğuyan ürünü boşalt',and(enabled(),no('WAIT_DONE'),no('COOL'),nc('EMPTY')),'DISCHARGE');}
 const off=Object.fromEntries(c.tags.filter(t=>t.address.startsWith('%Q')&&t.name!=='DONE').map(t=>[t.name,false]));
 const started:Record<string,Scalar>=batch?{VALVE:true,PUMP:false}:mix?{DOSE_A:true,DOSE_B:true,MIXER:false,DRAIN:false}:{DRUM:true,HEATER:true,FAN:false,DISCHARGE:false};
 test('STOP priority and restart','STOP önceliği ve yeniden başlatma',[step(0,{START:true,...(batch?{}:{LID_CLOSED:true}),EMPTY:false},started,'The cycle must start.','Çevrim başlamalı.'),step(100,{START:false,STOP:true},off,'STOP must switch off all actuators.','STOP bütün aktüatörleri kapatmalı.'),step(200,{STOP:false},off,'There must be no restart without a new START.','Yeni START olmadan yeniden çalışma olmamalı.')],'safety');
 test('Fault priority','Arıza önceliği',[step(0,{START:true,...(batch?{}:{LID_CLOSED:true}),FAULT:true},off,'The FAULT command must inhibit all actuators.','FAULT komutu bütün aktüatörleri engellemeli.')],'safety');
 if(!batch)test('Lid opened and closed again','Kapak açılması ve geri kapanması',[step(0,{START:true,...(batch?{}:{LID_CLOSED:true}),EMPTY:false},started,'Start','Başlat'),step(100,{START:false,LID_CLOSED:false},off,'Stop when the lid opens.','Kapak açılınca dur.'),step(200,{LID_CLOSED:true},off,'Closing the lid is not a substitute for START.','Kapak kapanması START yerine geçmez.')],'safety');
 if(batch)test('Fill → transfer → done → reset','Dolum → transfer → tamamlandı → reset',[step(0,{START:true,EMPTY:true},{VALVE:true,PUMP:false,DONE:false},'Filling must start.','Dolum başlamalı.'),step(100,{START:false,HIGH:true,EMPTY:false},{VALVE:false,PUMP:true},'Switch to draining at the upper level.','Üst seviyede boşaltmaya geç.'),step(200,{HIGH:false},{VALVE:false,PUMP:true},'The stage must be held when the level drops.','Seviye düşünce aşama korunmalı.'),step(300,{EMPTY:true},{...off,DONE:true},'The done flag must be held once the tank is empty.','Boş tankta tamamlandı bilgisi tutulmalı.'),step(400,{}, {...off,DONE:true},'DONE must be permanent.','DONE kalıcı olmalı.'),step(500,{RESET:true},{...off,DONE:false},'RESET must clear the done flag.','RESET tamamlandı bilgisini temizlemeli.')]);
 else if(mix)test('Dosing → mixing → draining','Dozaj → karıştırma → boşaltma',[step(0,{START:true,LID_CLOSED:true,EMPTY:true},started,'Both dosing valves must open.','İki dozaj valfi açılmalı.'),step(100,{START:false,A_READY:true,EMPTY:false},{DOSE_A:false,DOSE_B:true,MIXER:false},'A is done, B continues.','A tamam, B devam.'),step(200,{B_READY:true},{DOSE_A:false,DOSE_B:false,MIXER:true,DRAIN:false},'Both components are ready: mix.','İki bileşen hazır: karıştır.'),step(200+c.delay-10,{}, {MIXER:true,DRAIN:false},'No draining before PT has elapsed.','PT dolmadan boşaltma yok.'),step(200+c.delay,{}, {MIXER:false,DRAIN:true},'Drain when PT has elapsed.','PT sonunda boşalt.'),step(300+c.delay,{EMPTY:true},{...off,DONE:true},'Draining complete.','Boşaltma tamamlandı.'),step(400+c.delay,{RESET:true},{...off,DONE:false},'RESET makes it ready for a new batch.','RESET ile yeni partiye hazır.')]);
 else test('Heat → roast → cool → discharge','Isıt → kavur → soğut → boşalt',[step(0,{START:true,LID_CLOSED:true,COOL:true},started,'The loaded drum and the heater must run.','Yüklü tambur ve ısıtıcı çalışmalı.'),step(100,{START:false,HOT:true,COOL:false},{DRUM:true,HEATER:false,FAN:false},'The timer starts at the target temperature.','Hedef sıcaklıkta süre başlar.'),step(100+c.delay-10,{}, {FAN:false,DISCHARGE:false},'No cooling before the time has elapsed.','Süre dolmadan soğutma yok.'),step(100+c.delay,{}, {DRUM:true,HEATER:false,FAN:true,DISCHARGE:false},'Cool when the time has elapsed.','Süre sonunda soğut.'),step(200+c.delay,{HOT:false,COOL:true},{HEATER:false,FAN:false,DISCHARGE:true},'Discharge once cooled.','Soğuyunca boşalt.'),step(300+c.delay,{EMPTY:true},{...off,DONE:true},'Done once the discharge is finished.','Boşaltma sonunda tamamlandı.'),step(400+c.delay,{RESET:true},{...off,DONE:false},'RESET must not start the outputs.','RESET çıkışları başlatmaz.')]);
 break;}
 case 20:run();rung('Reject large products','Büyük ürün ayırma',and(no('RUN'),no('SENSOR'),no('LARGE')),'PUSHER');rung('Motion outside rejection','Ayırma dışında hareket',and(no('RUN'),or(nc('SENSOR'),nc('LARGE'))),'CONVEYOR');test('Sort by size','Boyuta göre ayırma',[step(0,{START:true},{CONVEYOR:true,PUSHER:false},'Start','Başlat'),step(100,{START:false,SENSOR:true,LARGE:false},{CONVEYOR:true,PUSHER:false},'Let the small product pass','Küçük ürünü geçir'),step(200,{LARGE:true},{CONVEYOR:false,PUSHER:true},'Reject the large product','Büyük ürünü ayır'),step(300,{SENSOR:false},{CONVEYOR:true,PUSHER:false},'Continue with the next product','Sonraki ürüne devam'),step(400,{OVERLOAD:true},{CONVEYOR:false,PUSHER:false},'Safe stop on a fault','Arızada güvenli duruş')],'safety');break;
 }
 return {public:c,reference:p,suites};
}
