export const modules=[
 ['PLC ve Scan Cycle','Giriş görüntüsü her scan başında alınır; network’ler sıralı yürütülür. Aynı scan içinde önceki yazılar sonraki network’te görülebilir.',1],
 ['NO / NC Contacts','NO tag TRUE iken, NC tag FALSE iken mantıksal geçiş sağlar. LAD NC ile fiziksel NC buton aynı şey değildir.',1],
 ['AND / OR Logic','Seri kontaklar bütün koşulları, paralel kollar alternatif koşulları ifade eder.',2],
 ['Start Stop Circuit','Durdurma sinyali başlatmadan önce değerlendirilmelidir. START ve STOP birlikteyken güvenli durum seçilir.',3],
 ['Seal-in','Motor kontağı START ile paralel durum tutar. Durdurma koşulları paralel grubun dışında bulunmalıdır.',4],
 ['Interlocks','Karşıt hareketleri birbirinin durumuyla engelle. Komutların birlikte gelmesini de test et.',6],
 ['Timers','TON gecikmeli açar; TOF gecikmeli kapatır; TP kenarda darbe üretir. PT hedef, ET geçen süredir.',7],
 ['Counters','CTU yükselen kenarları sayar. CU sürekli TRUE ise yeni ürün sayılmaz. RESET önceliklidir.',10],
 ['Sequence Control','Bir sıradaki adımları ayrı durumlar olarak temsil et. Her adımın çıkış ve geçiş koşulunu tanımla.',12],
 ['Analog Inputs','Ham aralığın anlamını modül yapılandırması belirler. Bu eğitimde sanal analog modül 0–27648 aralığı kullanır.',18],
 ['Scaling','NORM_X ile 0–1 oranını, SCALE_X ile mühendislik birimini bul. Aralık dışı sensörleri ayrıca değerlendir.',18],
 ['Motor Control','Ana kontaktör, yön kilidi ve arıza resetini birlikte düşün. Standart PLC güvenlik devresinin yerini almaz.',19],
 ['Conveyor Automation','Motor çıkışı ürünü hareket ettirir. Konumdan oluşan sensör, bir sonraki scan’de PLC girişine döner.',11],
 ['Tank Automation','İki eşikli dolum/boşaltma titreşimi önler. Çelişen sensörlerde durdurma önceliği belirle.',14],
 ['FB / FC / DB','FC kalıcı instance belleği olmadan çağrılan fonksiyondur. FB durumunu instance DB içinde tutar. Tam blok arayüzleri sonraki aşamadadır.',3],
 ['State Machines','Her durumun giriş, çıkış ve geçiş koşullarını açık yaz. Bir scan’de birden çok geçişin istenip istenmediğini belirle.',12],
 ['Industrial Troubleshooting','Semptomu bir giriş-zaman dizisine çevir. Başarısız scan’in mantık izini okuyarak kök nedeni bul.',3],
] as const;
