import {connectionError} from './connections';
import {type Block,type Program,type Diagnostic,type Value,walk,types} from './model';
import {blockLabel,blockName,dbOperands,identifier,localVar,vars} from './blocks';
import {address,validScalar} from './memory';
import type {Lang} from '../i18n/core';
import {plcTranslator} from '../i18n/dict/plc';
/** Diagnostic `code`s are stable; only `message` is localized (default English). */
export function compile(p:Program,lang:Lang='en'):Diagnostic[]{
 const t=plcTranslator(lang);const ds:Diagnostic[]=[]; const add=(code:string,message:string,network?:string,severity:'error'|'warning'='error')=>ds.push({code,message,network,severity});
 const tags=new Map(p.tags.map(t=>[t.name,t]));const ids=new Set<string>();const writes=new Map<string,string>();const virtuals=new Map<string,'BOOL'|'DINT'|'TIME'>();const instances=new Set<string>();const dbOps=dbOperands(p);
 for(const block of p.blocks)for(const network of block.networks)walk(network.logic,e=>{if(e.type==='CTU'||e.type==='CTD'||e.type==='CTUD'){const instance=e.instance?.trim();if(!instance)return;const key=instance.toLowerCase();if(instances.has(key))add('E035',t('diag.E035.counter',{name:instance}),network.id);instances.add(key);virtuals.set(`${key}.cv`,'DINT');if(e.type==='CTUD'){virtuals.set(`${key}.qu`,'BOOL');virtuals.set(`${key}.qd`,'BOOL');}else virtuals.set(`${key}.q`,'BOOL');}});
 for(const block of p.blocks)for(const network of block.networks)walk(network.logic,e=>{if(e.type==='TON'||e.type==='TOF'||e.type==='TP'){const instance=e.instance?.trim();if(!instance)return;const key=instance.toLowerCase();if(instances.has(key))add('E035',t('diag.E035.timer',{name:instance}),network.id);instances.add(key);virtuals.set(`${key}.q`,'BOOL');virtuals.set(`${key}.et`,'TIME');}});
 for(const tag of p.tags){if(!identifier.test(tag.name))add('E002',t('diag.E002',{name:tag.name}));try{address(tag.address,tag.type,lang);}catch(e){add('E003',e instanceof Error?e.message:String(e));}if(!validScalar(tag.type,tag.initial))add('E004',t('diag.E004',{name:tag.name,type:tag.type}));}
 if(tags.size!==p.tags.length)add('E005',t('diag.E005'));
 if(!p.blocks.some(b=>b.id==='OB1'))add('E010',t('diag.E010'));
 // Blocks: unique names, valid identifiers and interfaces, instance DBs bound to existing FBs.
 const names=new Set<string>();for(const b of p.blocks){const name=blockName(b);if(!identifier.test(name))add('E054',t('diag.E054',{name}));if(names.has(name.toLowerCase())||tags.has(name))add('E056',t('diag.E056',{name}));names.add(name.toLowerCase());
  for(const v of [...vars(b.iface),...(b.data??[])]){if(!identifier.test(v.name))add('E054',t('diag.E054',{name:`${name}.${v.name}`}));if(!validScalar(v.type,v.initial))add('E004',t('diag.E004',{name:`${name}.${v.name}`,type:v.type}));}
  if(b.kind==='DB'&&b.instanceOf&&p.blocks.find(x=>x.id===b.instanceOf)?.kind!=='FB')add('E055',t('diag.E055',{name}));}
 let block:Block=p.blocks[0];
 const operandType=(tag:string)=>tag.startsWith('#')?localVar(block,tag.slice(1))?.type:tags.get(tag)?.type??dbOps.get(tag)??virtuals.get(tag.toLowerCase());
 const ref=(tag:string,n:string,bool=false)=>{const type=operandType(tag);if(!type)add('E001',t('diag.E001',{tag}),n);else if(bool&&type!=='BOOL')add('E006',t('diag.E006.bool',{tag}),n);};
 const writable=(tag:string,n:string)=>{if(tag.startsWith('#')&&localVar(block,tag.slice(1))?.section==='constant')add('E057',t('diag.E057',{name:tag}),n);};
 const value=(v:Value,n:string):void=>{if(v.kind==='tag'){ref(v.tag,n);if(operandType(v.tag)==='BOOL')add('E006',t('diag.E006.numeric',{tag:v.tag}),n);}if(v.kind==='calc'){value(v.a,n);value(v.b,n);if(v.c)value(v.c,n);if(['NORM_X','SCALE_X'].includes(v.op)&&!v.c)add('E012',t('diag.E012',{op:v.op}),n);if(v.op==='DIV'&&v.b.kind==='literal'&&v.b.value===0)add('E013',t('diag.E013'),n);}};
 const mappedOutput=(tag:string,n:string,allowed:string[],label:string)=>{ref(tag,n);writable(tag,n);const type=operandType(tag);if(type&&!allowed.includes(type))add('E038',t('diag.E038',{tag,label,types:allowed.join('/')}),n);if(tags.get(tag)?.address.startsWith('%I'))add('E009',t('diag.E009.mapped',{label}),n);};
 const calls=new Map<string,Set<string>>();
 for(const b of p.blocks){block=b;calls.set(b.id,new Set());for(const n of b.networks){
 const pinKeys=new Set<string>();for(const c of n.connections??[]){const key=c.block+':'+c.pin;if(pinKeys.has(key))add('E041',t('diag.E041.single'),n.id);pinKeys.add(key);const error=connectionError(n,c,lang);if(error)add('E041',error,n.id);}
 if(n.output.unassigned)add('E015',t('diag.E015'),n.id);
 if(n.output.type==='CALL'){const o=n.output,callee=p.blocks.find(x=>x.id===o.tag);if(!callee||(callee.kind!=='FC'&&callee.kind!=='FB'))add('E050',t('diag.E050',{name:o.tag}),n.id);else{calls.get(b.id)!.add(callee.id);const label=blockLabel(callee);if(callee.kind==='FB'){const db=p.blocks.find(x=>x.id===o.instance);if(!db||db.kind!=='DB'||db.instanceOf!==callee.id)add('E051',t('diag.E051',{name:label}),n.id);}
  const ins=vars(callee.iface,['input','inout']),outs=vars(callee.iface,['output']);
  for(const [param,v] of Object.entries(o.params??{})){const decl=ins.find(x=>x.name===param);if(!decl)add('E052',t('diag.E052',{block:label,param}),n.id);else if(v.kind==='tag')ref(v.tag,n.id,decl.type==='BOOL');else if(decl.type!=='BOOL')value(v,n.id);}
  for(const [param,dest] of Object.entries(o.outs??{})){const decl=outs.find(x=>x.name===param);if(!decl)add('E052',t('diag.E052',{block:label,param}),n.id);else if(dest){ref(dest,n.id,decl.type==='BOOL');writable(dest,n.id);if(tags.get(dest)?.address.startsWith('%I'))add('E009',t('diag.E009.output'),n.id);}}}}
 else{ref(n.output.tag,n.id,n.output.type!=='MOVE');writable(n.output.tag,n.id);const target=tags.get(n.output.tag);
 if(target?.address.startsWith('%I'))add('E009',t('diag.E009.output'),n.id);
 if(n.output.type==='MOVE'){if(!n.output.value)add('E011',t('diag.E011'),n.id);else value(n.output.value,n.id);if(operandType(n.output.tag)==='BOOL')add('E006',t('diag.E006.moveTarget'),n.id);}
 const key=(n.output.tag.startsWith('#')?`${b.id}:`:'')+(target?.address??n.output.tag);if(writes.has(key)&&n.output.type==='COIL')add('W021',t('diag.W021',{address:key}),n.id,'warning');writes.set(key,n.id);}
 walk(n.logic,e=>{if(ids.has(e.id))add('E034',t('diag.E034',{id:e.id}),n.id);ids.add(e.id);if('tag'in e)ref(e.tag,n.id,true);if('children'in e&&!e.pin&&e.children.length===0&&!(e===n.logic&&(n.output.type==='CALL'||n.output.type==='MOVE')))add('E014',t('diag.E014'),n.id);if('pt'in e){if(typeof e.pt==='number'){if(!Number.isInteger(e.pt)||e.pt<0||e.pt>2147483647)add('E030',t('diag.E030'),n.id);}else{value(e.pt,n.id);if(e.pt.kind==='tag'&&operandType(e.pt.tag)!=='TIME')add('E037',t('diag.E037',{tag:e.pt.tag}),n.id);}if(e.instance!==undefined&&!identifier.test(e.instance))add('E036',t('diag.E036.timer',{name:e.instance}),n.id);}if('pv'in e){if(typeof e.pv==='number'){if(!Number.isInteger(e.pv)||e.pv<-2147483648||e.pv>2147483647)add('E031',t('diag.E031'),n.id);}else value(e.pv,n.id);if(e.instance!==undefined&&!identifier.test(e.instance))add('E036',t('diag.E036.counter',{name:e.instance}),n.id);}if('etTag'in e&&e.etTag)mappedOutput(e.etTag,n.id,['TIME'],'ET');if('cvTag'in e&&e.cvTag)mappedOutput(e.cvTag,n.id,['INT','DINT','WORD','DWORD'],'CV');if(e.type==='COMPARE'){value(e.a,n.id);value(e.b,n.id);}if(e.type==='AND'){const a=e.children.filter(x=>x.type==='NO').map(x=>'tag'in x?x.tag:'');if(e.children.some(x=>x.type==='NC'&&a.includes(x.tag)))add('W040',t('diag.W040'),n.id,'warning');}});
 }}
 // Call graph: no recursion; FC/FB that no OB reaches only get a warning (they never run).
 const reached=new Set<string>(),visit=(id:string,path:string[]):void=>{if(path.includes(id)){add('E053',t('diag.E053',{name:id}));return;}if(reached.has(id))return;reached.add(id);for(const next of calls.get(id)??[])visit(next,[...path,id]);};
 for(const b of p.blocks)if(b.kind==='OB')visit(b.id,[]);
 for(const b of p.blocks)if((b.kind==='FC'||b.kind==='FB')&&!reached.has(b.id))add('W061',t('diag.W061',{name:blockLabel(b)}),undefined,'warning');
 return ds;
}
// Untrusted imported programs and API submissions are bounded before recursive execution.
export function parseProgram(raw:unknown,lang:Lang='en'):Program {
 const msg=plcTranslator(lang);let count=0;const obj=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error(msg('parse.object'));return v as Record<string,unknown>;};
 const str=(v:unknown)=>{if(typeof v!=='string'||v.length>300)throw Error(msg('parse.text'));return v;};
 const num=(v:unknown)=>{if(typeof v!=='number'||!Number.isFinite(v))throw Error(msg('parse.number'));return v;};
 const val=(v:unknown,d=0):void=>{if(d>12)throw Error(msg('parse.operandDepth'));const o=obj(v);if(o.kind==='literal')num(o.value);else if(o.kind==='tag')str(o.tag);else if(o.kind==='calc'&&['ADD','SUB','MUL','DIV','INT_TO_REAL','REAL_TO_INT','WORD_TO_INT','NORM_X','SCALE_X'].includes(String(o.op))){val(o.a,d+1);val(o.b,d+1);if(o.c)val(o.c,d+1);}else throw Error(msg('parse.operand'));};
 const expr=(v:unknown,d=0):void=>{if(++count>800||d>15)throw Error(msg('parse.complexity'));const e=obj(v);str(e.id);switch(e.type){case'NO':case'NC':case'P':case'N':str(e.tag);break;case'AND':case'OR':if(!Array.isArray(e.children))throw Error(msg('parse.children'));e.children.forEach(x=>expr(x,d+1));break;case'TON':case'TOF':case'TP':if(e.instance!==undefined)str(e.instance);if(e.etTag!==undefined)str(e.etTag);if(typeof e.pt==='number')num(e.pt);else val(e.pt);expr(e.input,d+1);break;case'CTU':if(e.instance!==undefined)str(e.instance);if(e.cvTag!==undefined)str(e.cvTag);if(typeof e.pv==='number')num(e.pv);else val(e.pv);expr(e.input,d+1);expr(e.reset,d+1);break;case'CTD':if(e.instance!==undefined)str(e.instance);if(e.cvTag!==undefined)str(e.cvTag);if(typeof e.pv==='number')num(e.pv);else val(e.pv);expr(e.input,d+1);expr(e.load,d+1);break;case'CTUD':if(e.instance!==undefined)str(e.instance);if(e.cvTag!==undefined)str(e.cvTag);if(typeof e.pv==='number')num(e.pv);else val(e.pv);expr(e.input,d+1);expr(e.down,d+1);expr(e.reset,d+1);expr(e.load,d+1);break;case'R_TRIG':case'F_TRIG':expr(e.input,d+1);break;case'COMPARE':if(!['==','<>','>','<','>=','<='].includes(String(e.op)))throw Error(msg('parse.compare'));val(e.a);val(e.b);break;default:throw Error(msg('parse.instruction'));}};
 const p=obj(raw);if(p.version!==1||!Array.isArray(p.tags)||!Array.isArray(p.blocks)||p.tags.length>256||p.blocks.length>60)throw Error(msg('parse.format'));str(p.cpu);
 for(const x of p.tags){const t=obj(x);str(t.name);str(t.address);str(t.comment);if(t.inputMode!==undefined&&!['toggle','momentary'].includes(String(t.inputMode)))throw Error(msg('parse.inputMode'));if(!types.includes(t.type as never)||!validScalar(t.type as never,t.initial))throw Error(msg('parse.tagType'));}
 const blockIds=new Set();const networkIds=new Set();for(const x of p.blocks){const b=obj(x);str(b.id);if(blockIds.has(b.id))throw Error(msg('parse.blockDuplicate'));blockIds.add(b.id);if(!['OB','FC','FB','DB'].includes(String(b.kind))||!Array.isArray(b.networks)||b.networks.length>100)throw Error(msg('parse.blockFormat'));for(const k of ['name','title','instanceOf'])if(b[k]!==undefined)str(b[k]);if(b.number!==undefined&&(!Number.isInteger(b.number)||Number(b.number)<1||Number(b.number)>65535))throw Error(msg('parse.blockFormat'));if(b.obType!==undefined&&!['cycle','startup'].includes(String(b.obType)))throw Error(msg('parse.blockFormat'));const vlist=(v:unknown)=>{if(!Array.isArray(v)||v.length>128)throw Error(msg('parse.interface'));for(const x of v){const d=obj(x);str(d.name);str(d.comment);if(!types.includes(d.type as never)||!validScalar(d.type as never,d.initial))throw Error(msg('parse.interface'));}};if(b.data!==undefined)vlist(b.data);if(b.iface!==undefined){const f=obj(b.iface);for(const [k,v] of Object.entries(f)){if(!['input','output','inout','static','temp','constant'].includes(k))throw Error(msg('parse.interface'));vlist(v);}}for(const y of b.networks){const n=obj(y);str(n.id);if(networkIds.has(n.id))throw Error(msg('parse.networkDuplicate'));networkIds.add(n.id);str(n.title);expr(n.logic);if(n.connections!==undefined){if(!Array.isArray(n.connections)||n.connections.length>800)throw Error(msg('parse.connections'));for(const raw of n.connections){const c=obj(raw);str(c.block);str(c.source);if(!['reset','load','down'].includes(String(c.pin))||!['before','after'].includes(String(c.side)))throw Error(msg('parse.pin'));}}const o=obj(n.output);str(o.tag);if(o.unassigned!==undefined&&typeof o.unassigned!=='boolean')throw Error(msg('parse.scaffold'));if(!['COIL','SET','RESET','MOVE','CALL'].includes(String(o.type)))throw Error(msg('parse.outputType'));if(o.type==='MOVE')val(o.value);if(o.type==='CALL'){if(o.instance!==undefined)str(o.instance);if(o.params!==undefined){const ps=obj(o.params);if(Object.keys(ps).length>64)throw Error(msg('parse.call'));for(const v of Object.values(ps))val(v);}if(o.outs!==undefined){const os=obj(o.outs);if(Object.keys(os).length>64)throw Error(msg('parse.call'));for(const v of Object.values(os))str(v);}}}}
 return raw as Program;
}
