'use client';
import {useState,useEffect} from 'react';
import {Plus,Trash2,ArrowUp,ArrowDown,GitBranch,MousePointer2} from 'lucide-react';
import {blankNetwork,uid,type Expr,type Network,type Tag,type Trace} from '../plc/model';
import {find,replace,remove,insert,moveNode} from './editing';
import {Choice} from '../ui/Choice';
import {ValueEditor} from './ValueEditor';
type Props={onCommandDone?:()=>void;command?:{kind:string;nonce:number};networks:Network[];tags:Tag[];trace:Record<string,Trace>;monitor:boolean;locked:boolean;onChange:(ns:Network[])=>void;onWhy:(id:string)=>void};
function Symbol({type}:{type:string}){return <svg width="72" height="38" viewBox="0 0 72 38" aria-hidden="true"><path d="M0 19H24 M48 19H72" fill="none" stroke="currentColor" strokeWidth="2"/>{['NO','NC'].includes(type)?<><path d="M25 6V32 M47 6V32" stroke="currentColor" strokeWidth="2"/>{type==='NC'&&<path d="M29 31L43 7" stroke="currentColor" strokeWidth="2"/>}</>:<><path d="M31 5Q16 19 31 33 M41 5Q56 19 41 33" stroke="currentColor" fill="none" strokeWidth="2"/>{type!=='COIL'&&<text x="36" y="24" textAnchor="middle" fill="currentColor" fontSize="12">{type==='SET'?'S':type==='RESET'?'R':'='}</text>}</>}</svg>;}
function ExprView({addresses,expr,selected,onSelect,onWhy,onMove,trace,monitor,powered,locked}:{addresses:Record<string,string>;expr:Expr;selected:string;onSelect:(e:Expr)=>void;onWhy:(id:string)=>void;onMove:(a:string,b:string)=>void;trace:Record<string,Trace>;monitor:boolean;powered:boolean;locked:boolean}){
 const active=monitor&&powered&&!!trace[expr.id]?.value;
 const props={addresses,selected,onSelect,onWhy,onMove,trace,monitor,locked};
 if('children'in expr){let power=powered;return <div className={`logic-group ${expr.type.toLowerCase()} ${active?'energized':''}`}><button className={`group-label ${selected===expr.id?'chosen':''}`} disabled={locked} onClick={()=>onSelect(expr)}>{expr.type==='AND'?'SERİ':'PARALEL'}</button>{expr.children.length?expr.children.map(child=>{const incoming=power;if(expr.type==='AND')power=power&&!!trace[child.id]?.value;return <div className="logic-path" key={child.id}><ExprView {...props} expr={child} powered={expr.type==='AND'?incoming:powered}/></div>;}):<button className="empty-path" onClick={()=>onSelect(expr)} disabled={locked}>＋ Bu yola eleman ekle</button>}</div>;}
 return <div className={`instruction-wrap ${active?'energized':''}`}><button className={`instruction ${selected===expr.id?'chosen':''}`} draggable={!locked} onDragStart={event=>event.dataTransfer.setData('text/plain',expr.id)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(!locked)onMove(event.dataTransfer.getData('text/plain'),expr.id);}} onClick={()=>onSelect(expr)} onContextMenu={event=>{event.preventDefault();onWhy(expr.id);}} title="Seçmek için tıkla; mantık izini görmek için sağ tıkla"><span className="tag-label">{'tag'in expr?<><b>{addresses[expr.tag]}</b><span>"{expr.tag}"</span></>:expr.type}</span>{'tag'in expr?<Symbol type={expr.type}/>:<span className="function-symbol">{expr.type}</span>}<span className="instruction-value">{monitor?trace[expr.id]?.value?'TRUE':'FALSE':'tag'in expr?expr.type:'pt'in expr?`PT ${expr.pt} ms`:'pv'in expr?`PV ${expr.pv}`:'logic'}</span></button>{'input'in expr&&<div className="function-inputs"><label>IN<ExprView {...props} expr={expr.input} powered={powered}/></label>{'reset'in expr&&<label>R<ExprView {...props} expr={expr.reset} powered={powered}/></label>}{monitor&&<small>{trace[expr.id]?.detail}</small>}</div>}</div>;
}
export default function Editor({onCommandDone,command,networks,tags,trace,monitor,locked,onChange,onWhy}:Props){
 const [selection,setSelection]=useState<{network:string;node:string}>({network:'',node:''});const [palette,setPalette]=useState('NO');
 const n=networks.find(x=>x.id===selection.network),selected=n?find(n.logic,selection.node):undefined;
 const bools=tags.filter(t=>t.type==='BOOL').map(t=>t.name),outTags=tags.filter(t=>!t.address.startsWith('%I'));
 const update=(id:string,changes:Partial<Network>)=>onChange(networks.map(x=>x.id===id?{...x,...changes}:x));
 const modify=(change:(e:Expr)=>Expr)=>{if(n&&selected)update(n.id,{logic:replace(n.logic,selected.id,change)});};
 const make=(kind=palette):Expr=>{const input:Expr={id:uid(),type:'NO',tag:bools[0]??'START'};if(kind==='NO'||kind==='NC')return {...input,type:kind};if(kind==='TON'||kind==='TOF'||kind==='TP')return {id:uid(),type:kind,pt:1000,input};if(kind==='CTU')return {id:uid(),type:'CTU',pv:3,input,reset:{id:uid(),type:'NO',tag:bools.find(t=>t==='RESET')??bools[1]??'STOP'}};if(kind==='COMPARE')return {id:uid(),type:'COMPARE',op:'>',a:{kind:'tag',tag:'RAW'},b:{kind:'literal',value:0}};return {id:uid(),type:kind as 'R_TRIG'|'F_TRIG',input};};
 const add=(parallel=false,kind=palette)=>{const target=n??networks[networks.length-1];const node=make(kind);if(!target){const net=blankNetwork(outTags.find(t=>t.type==='BOOL')?.name);net.logic=node;onChange([...networks,net]);setSelection({network:net.id,node:node.id});}else{update(target.id,{logic:insert(target.logic,selected?.id,node,parallel)});setSelection({network:target.id,node:node.id});}};
 useEffect(()=>{if(!command||locked)return;const kind=command.kind;if(['COIL','SET','RESET','MOVE','ADD','SUB','MUL','DIV','INT_TO_REAL','REAL_TO_INT','WORD_TO_INT','NORM_X','SCALE_X'].includes(kind)){const target=n??networks[networks.length-1]??blankNetwork();const coil=['COIL','SET','RESET'].includes(kind);const output:Network['output']=coil?{type:kind as 'COIL'|'SET'|'RESET',tag:target.output.tag}:{type:'MOVE',tag:'TEMP',value:kind==='MOVE'?{kind:'tag',tag:'RAW'}:{kind:'calc',op:kind as 'ADD',a:{kind:'tag',tag:'RAW'},b:{kind:'literal',value:1},c:{kind:'literal',value:150}}};if(networks.some(x=>x.id===target.id))update(target.id,{output});else onChange([...networks,{...target,output}]);setSelection({network:target.id,node:target.id});}else if(kind.startsWith('CMP ')){const target=n??networks[networks.length-1]??blankNetwork();const node:Expr={id:uid(),type:'COMPARE',op:kind.slice(4) as '==',a:{kind:'tag',tag:'RAW'},b:{kind:'literal',value:0}};if(networks.some(x=>x.id===target.id))update(target.id,{logic:insert(target.logic,selected?.id,node)});else onChange([...networks,{...target,logic:node}]);setSelection({network:target.id,node:node.id});}else add(false,kind);onCommandDone?.();},[command?.nonce]);
 return <div className="ladder-editor"><div className="instruction-ribbon"><div className="ribbon-group"><small>KONTAKLAR</small><div>{[['NO','—| |—'],['NC','—|/|—'],['R_TRIG','—|P|—'],['F_TRIG','—|N|—']].map(([kind,symbol])=><button key={kind} disabled={locked} title={`${kind} seri ekle`} onClick={()=>{setPalette(kind);add(false,kind);}}><strong>{symbol}</strong><span>{kind}</span></button>)}</div></div><div className="ribbon-group"><small>BOBİNLER</small><div>{[['COIL','—( )—'],['SET','—(S)—'],['RESET','—(R)—']].map(([kind,symbol])=><button key={kind} disabled={locked} onClick={()=>{const target=n??networks[networks.length-1];if(target){update(target.id,{output:{...target.output,type:kind as Network['output']['type']}});setSelection({network:target.id,node:target.id});}else{const net=blankNetwork(outTags.find(t=>t.type==='BOOL')?.name);net.output.type=kind as Network['output']['type'];onChange([...networks,net]);setSelection({network:net.id,node:net.id});}}}><strong>{symbol}</strong><span>{kind}</span></button>)}</div></div><div className="ribbon-group"><small>TIMERS / COUNTERS</small><div>{['TON','TOF','TP','CTU'].map(kind=><button key={kind} disabled={locked} onClick={()=>{setPalette(kind);add(false,kind);}}><strong className="block-icon">{kind}</strong><span>{kind==='CTU'?'Counter':'IEC timer'}</span></button>)}</div></div><div className="ribbon-group"><small>BAĞLANTI / COMPARE</small><div><button disabled={locked} onClick={()=>add(true)}><GitBranch size={22}/><span>Paralel</span></button><button disabled={locked} onClick={()=>add(false)}><Plus size={22}/><span>Seri</span></button><button disabled={locked} onClick={()=>add(false,'COMPARE')}><strong>≥ ≤</strong><span>Compare</span></button><button disabled={locked||!selected} onClick={()=>{if(n)update(n.id,{logic:remove(n.logic,selection.node)});}} aria-label="Seçili elemanı sil"><Trash2 size={22}/><span>Sil</span></button></div></div></div><div className="ribbon-secondary"><MousePointer2 size={13}/><span>Elemanı seç → komuta tıkla → tag ata. Paralel: seçili elemana alternatif yol ekler.</span><button disabled={locked||!n} onClick={()=>{if(n){update(n.id,{output:{type:'MOVE',tag:'TEMP',value:{kind:'literal',value:0}}});setSelection({network:n.id,node:n.id});}}}>MOVE / Math / Conversion</button></div>
 <div className="ladder-canvas">{networks.length===0&&<div className="empty-editor"><GitBranch size={32}/><h2>İlk network’ünü kur</h2><p>NO / NC kontaklarını seçip seri veya paralel ekle. Çıkış bobininin tag’ini ata.</p><button className="primary" onClick={()=>onChange([blankNetwork(outTags.find(t=>t.type==='BOOL')?.name)])} disabled={locked}>＋ Network ekle</button></div>}
 {networks.map((net,index)=><section className="network" id={`network-${net.id}`} key={net.id}><div className="networkhead"><b>Network {index+1}</b><input aria-label={`Network ${index+1} açıklaması`} value={net.title} disabled={locked} onChange={e=>update(net.id,{title:e.target.value})}/><button aria-label="Network yukarı" disabled={locked||index===0} onClick={()=>{const ns=[...networks];[ns[index-1],ns[index]]=[ns[index],ns[index-1]];onChange(ns);}}><ArrowUp size={13}/></button><button aria-label="Network aşağı" disabled={locked||index===networks.length-1} onClick={()=>{const ns=[...networks];[ns[index+1],ns[index]]=[ns[index],ns[index+1]];onChange(ns);}}><ArrowDown size={13}/></button><button aria-label="Network sil" disabled={locked} onClick={()=>onChange(networks.filter(x=>x.id!==net.id))}><Trash2 size={13}/></button></div><div className="rung-scroll"><div className="rung"><div className={`power-rail ${monitor?'energized':''}`}/><ExprView addresses={Object.fromEntries(tags.map(t=>[t.name,t.address]))} expr={net.logic} {...{trace,monitor,locked}} selected={selection.node} onSelect={e=>setSelection({network:net.id,node:e.id})} onWhy={onWhy} powered={true} onMove={(a,b)=>update(net.id,{logic:moveNode(net.logic,a,b)})}/><div className={`output-wire ${monitor&&trace[net.id]?.value?'energized':''}`}/><button className={`coil-node ${monitor&&trace[net.id]?.value?'energized':''} ${selection.node===net.id?'chosen':''}`} onClick={()=>setSelection({network:net.id,node:net.id})} onContextMenu={e=>{e.preventDefault();onWhy(net.id);}}><span className="tag-label"><b>{tags.find(t=>t.name===net.output.tag)?.address}</b><span>"{net.output.tag}"</span></span>{net.output.type==='MOVE'?<span className="move-instruction"><b>{net.output.value?.kind==='calc'?net.output.value.op:'MOVE'}</b><span>EN ─── ENO</span><span>IN ─── OUT</span></span>:<Symbol type={net.output.type}/>}<small>{net.output.type}</small></button><div className="power-rail"/></div></div>{monitor&&trace[net.id]&&<div className="network-trace">{trace[net.id].detail}</div>}</section>)}{networks.length>0&&<button className="add-network" disabled={locked} onClick={()=>onChange([...networks,blankNetwork(outTags.find(t=>t.type==='BOOL')?.name)])}><Plus size={15}/>Network ekle</button>}</div>
 {n&&<div className="instruction-inspector"><b>ELEMENT ÖZELLİKLERİ</b>{selected?<><span className="pill">{selected.type}</span>{'tag'in selected&&<><Choice label="Kontak türü" value={selected.type} options={['NO','NC']} disabled={locked} onChange={type=>modify(e=>({...e,type} as Expr))}/><Choice label="Kontak tag" value={selected.tag} options={bools} disabled={locked} onChange={tag=>modify(e=>({...e,tag} as Expr))}/></>}{'pt'in selected&&<label>PT (ms)<input disabled={locked} type="number" min="0" max="3600000" value={selected.pt} onChange={e=>modify(x=>({...x,pt:Number(e.target.value)} as Expr))}/></label>}{'pv'in selected&&<label>PV<input disabled={locked} type="number" min="1" max="32767" value={selected.pv} onChange={e=>modify(x=>({...x,pv:Number(e.target.value)} as Expr))}/></label>}{selected.type==='COMPARE'&&<fieldset disabled={locked}><Choice label="Karşılaştırma" value={selected.op} options={['==','<>','>','<','>=','<=']} onChange={op=>modify(e=>({...e,op} as Expr))}/><ValueEditor value={selected.a} tags={tags} onChange={a=>modify(e=>({...e,a} as Expr))}/><ValueEditor value={selected.b} tags={tags} onChange={b=>modify(e=>({...e,b} as Expr))}/></fieldset>}{'children'in selected&&<Choice label="Grup mantığı" value={selected.type} options={['AND','OR']} disabled={locked} onChange={type=>modify(e=>({...e,type} as Expr))}/>}<button onClick={()=>onWhy(selected.id)}>Why TRUE / FALSE?</button></>:<><Choice label="Çıkış instruction" value={n.output.type} options={['COIL','SET','RESET','MOVE']} disabled={locked} onChange={type=>update(n.id,{output:{...n.output,type:type as Network['output']['type'],value:n.output.value??{kind:'literal',value:0}}})}/><Choice label="Çıkış tag" value={n.output.tag} options={outTags.filter(t=>n.output.type==='MOVE'?t.type!=='BOOL':t.type==='BOOL').map(t=>t.name)} disabled={locked} onChange={tag=>update(n.id,{output:{...n.output,tag}})}/>{n.output.type==='MOVE'&&<fieldset disabled={locked}><ValueEditor value={n.output.value??{kind:'literal',value:0}} tags={tags} onChange={value=>update(n.id,{output:{...n.output,value}})}/></fieldset>}</>}</div>}
 </div>;
}



