'use client';
import {useState,useEffect} from 'react';
import {Plus,Trash2,ArrowUp,ArrowDown,GitBranch,MousePointer2} from 'lucide-react';
import {blankNetwork,walk,type CounterExpr,type Expr,type Network,type Tag,type Trace} from '../plc/model';
import {find,replace,remove,insert,moveNode} from './editing';
import {Choice} from '../ui/Choice';
import {ValueEditor} from './ValueEditor';
import Rung from './Rung';
import {InstructionIcon,instructionHelp} from './InstructionIcon';
import {booleanOutput,logicInstruction,numericOutput,type NumericInstruction} from './instructionFactory';
type Props={onCommandDone?:()=>void;command?:{kind:string;nonce:number};networks:Network[];tags:Tag[];trace:Record<string,Trace>;monitor:boolean;locked:boolean;onChange:(ns:Network[])=>void;onWhy:(id:string)=>void};
export default function Editor({onCommandDone,command,networks,tags,trace,monitor,locked,onChange,onWhy}:Props){
 const [selection,setSelection]=useState<{network:string;node:string;before?:boolean}>({network:'',node:''});const [palette,setPalette]=useState('NO');const [collapsed,setCollapsed]=useState<Set<string>>(()=>new Set());
 const n=networks.find(x=>x.id===selection.network),selected=n?find(n.logic,selection.node):undefined;
 const counterBools:string[]=[];for(const network of networks)walk(network.logic,e=>{if((e.type==='CTU'||e.type==='CTD'||e.type==='CTUD')&&e.instance){if(e.type==='CTUD')counterBools.push(`${e.instance}.QU`,`${e.instance}.QD`);else counterBools.push(`${e.instance}.Q`);}});const bools=[...tags.filter(t=>t.type==='BOOL').map(t=>t.name),...new Set(counterBools)],outTags=tags.filter(t=>!t.address.startsWith('%I'));
 const update=(id:string,changes:Partial<Network>)=>onChange(networks.map(x=>x.id===id?{...x,...changes}:x));
 const modify=(change:(e:Expr)=>Expr)=>{if(n&&selected)update(n.id,{logic:replace(n.logic,selected.id,change)});};
 const make=(kind=palette):Expr=>logicInstruction(kind as Parameters<typeof logicInstruction>[0],tags);
 const add=(parallel=false,kind=palette)=>{const target=n??networks[networks.length-1];const node=make(kind);if(!target){const net=blankNetwork(outTags.find(t=>t.type==='BOOL')?.name);net.logic=node;onChange([...networks,net]);setSelection({network:net.id,node:node.id});}else{update(target.id,{logic:insert(target.logic,selected?.id,node,parallel,selection.before)});setSelection({network:target.id,node:node.id});}};
 useEffect(()=>{if(!command||locked)return;const kind=command.kind;if(['COIL','SET','RESET','MOVE','ADD','SUB','MUL','DIV','INT_TO_REAL','REAL_TO_INT','WORD_TO_INT','NORM_X','SCALE_X'].includes(kind)){const target=n??networks[networks.length-1]??blankNetwork();const output:Network['output']=['COIL','SET','RESET'].includes(kind)?booleanOutput(kind as 'COIL'|'SET'|'RESET',tags,target.output):numericOutput(kind as NumericInstruction,tags,target.output);if(networks.some(x=>x.id===target.id))update(target.id,{output});else onChange([...networks,{...target,output}]);setSelection({network:target.id,node:target.id});}else if(kind.startsWith('CMP ')){const target=n??networks[networks.length-1]??blankNetwork();const node=logicInstruction('COMPARE',tags,kind.slice(4) as '=='|'<>'|'>'|'<'|'>='|'<=');if(networks.some(x=>x.id===target.id))update(target.id,{logic:insert(target.logic,selected?.id,node,false,selection.before)});else onChange([...networks,{...target,logic:node}]);setSelection({network:target.id,node:node.id});}else add(false,kind);onCommandDone?.();},[command?.nonce]);
 return <div className="ladder-editor"><div className="instruction-ribbon"><div className="ribbon-group"><small>KONTAKLAR</small><div>{[['NO','—| |—'],['NC','—|/|—'],['R_TRIG','—|P|—'],['F_TRIG','—|N|—']].map(([kind,symbol])=><button key={kind} disabled={locked} title={instructionHelp[kind]} aria-label={kind} onClick={()=>{setPalette(kind);add(false,kind);}}><InstructionIcon kind={kind}/><span>{kind}</span></button>)}</div></div><div className="ribbon-group"><small>BOBİNLER</small><div>{[['COIL','—( )—'],['SET','—(S)—'],['RESET','—(R)—']].map(([kind,symbol])=><button key={kind} title={instructionHelp[kind]} aria-label={kind} disabled={locked} onClick={()=>{const target=n??networks[networks.length-1];if(target){update(target.id,{output:{...target.output,unassigned:false,type:kind as Network['output']['type']}});setSelection({network:target.id,node:target.id});}else{const net=blankNetwork(outTags.find(t=>t.type==='BOOL')?.name);net.output.unassigned=false;net.output.type=kind as Network['output']['type'];onChange([...networks,net]);setSelection({network:net.id,node:net.id});}}}><InstructionIcon kind={kind}/><span>{kind}</span></button>)}</div></div><div className="ribbon-group"><small>TIMERS / COUNTERS</small><div>{['TON','TOF','TP','CTU','CTD','CTUD'].map(kind=><button key={kind} title={instructionHelp[kind]} aria-label={kind} disabled={locked} onClick={()=>{setPalette(kind);add(false,kind);}}><InstructionIcon kind={kind}/><span>{kind.startsWith('CT')?'Counter':'IEC timer'}</span></button>)}</div></div><div className="ribbon-group"><small>BAĞLANTI / COMPARE</small><div><button title="Paralel kol ekle" aria-label="Paralel kol ekle" disabled={locked} onClick={()=>add(true)}><GitBranch size={22}/><span>Paralel</span></button><button title="Seri kontak ekle" aria-label="Seri kontak ekle" disabled={locked} onClick={()=>add(false)}><Plus size={22}/><span>Seri</span></button><button disabled={locked} onClick={()=>add(false,'COMPARE')}><strong>≥ ≤</strong><span>Compare</span></button><button disabled={locked||!selected} onClick={()=>{if(n)update(n.id,{logic:remove(n.logic,selection.node)});}} aria-label="Seçili elemanı sil"><Trash2 size={22}/><span>Sil</span></button></div></div></div><div className="ribbon-secondary"><MousePointer2 size={13}/><span>Elemanı seç → komuta tıkla → tag ata. Paralel: seçili elemana alternatif yol ekler.</span><button disabled={locked||!n} onClick={()=>{if(n){update(n.id,{output:{type:'MOVE',tag:'TEMP',value:{kind:'literal',value:0}}});setSelection({network:n.id,node:n.id});}}}>MOVE / Math / Conversion</button></div>
 <div className="block-title">▾ <b>Block title:</b> “Main Program Sweep (Cycle)”</div><div className="block-comment">Comment</div><div className="ladder-canvas">{networks.length===0&&<div className="empty-editor"><GitBranch size={32}/><h2>İlk network’ünü kur</h2><p>NO / NC kontaklarını seçip seri veya paralel ekle. Çıkış bobininin tag’ini ata.</p><button className="primary" onClick={()=>onChange([blankNetwork(outTags.find(t=>t.type==='BOOL')?.name)])} disabled={locked}>＋ Network ekle</button></div>}
 {networks.map((net,index)=>{const isCollapsed=collapsed.has(net.id);return <section className={`network${isCollapsed?' network-collapsed':''}`} id={`network-${net.id}`} key={net.id}><div className="networkhead"><button className="network-collapse" aria-label={`Network ${index+1} ${isCollapsed?'aç':'kapat'}`} onClick={()=>setCollapsed(current=>{const next=new Set(current);if(next.has(net.id))next.delete(net.id);else next.add(net.id);return next;})}>{isCollapsed?'▸':'▾'}</button><b>Network {index+1}</b><input aria-label={`Network ${index+1} açıklaması`} value={net.title} disabled={locked} onChange={e=>update(net.id,{title:e.target.value})}/><button aria-label="Network yukarı" disabled={locked||index===0} onClick={()=>{const ns=[...networks];[ns[index-1],ns[index]]=[ns[index],ns[index-1]];onChange(ns);}}><ArrowUp size={13}/></button><button aria-label="Network aşağı" disabled={locked||index===networks.length-1} onClick={()=>{const ns=[...networks];[ns[index+1],ns[index]]=[ns[index],ns[index+1]];onChange(ns);}}><ArrowDown size={13}/></button><button aria-label="Network sil" disabled={locked} onClick={()=>onChange(networks.filter(x=>x.id!==net.id))}><Trash2 size={13}/></button></div>{!isCollapsed&&<><input className="network-comment" aria-label={`Network ${index+1} comment`} placeholder="Comment" value={net.comment??''} disabled={locked} onChange={e=>update(net.id,{comment:e.target.value})}/><div className="rung-scroll"><Rung network={net} tags={tags} trace={trace} monitor={monitor} locked={locked} selected={selection.node} onSelect={id=>setSelection({network:net.id,node:id})} onWhy={onWhy} onInsert={(id,before)=>setSelection({network:net.id,node:id,before})} onTag={(id,tag)=>id===net.id?update(net.id,{output:{...net.output,unassigned:false,tag}}):update(net.id,{logic:replace(net.logic,id,e=>({...e,tag} as Expr))})} onMove={(a,b)=>update(net.id,{logic:moveNode(net.logic,a,b)})}/></div>{monitor&&trace[net.id]&&<div className="network-trace">{trace[net.id].detail}</div>}</>}</section>})}{networks.length>0&&<button className="add-network" disabled={locked} onClick={()=>onChange([...networks,blankNetwork(outTags.find(t=>t.type==='BOOL')?.name)])}><Plus size={15}/>Network ekle</button>}</div>
 {n&&<div className="instruction-inspector"><b>ELEMENT ÖZELLİKLERİ</b>{selected?<><span className="pill">{selected.type}</span>{'tag'in selected&&<><Choice label="Kontak türü" value={selected.type} options={['NO','NC']} disabled={locked} onChange={type=>modify(e=>({...e,type} as Expr))}/><Choice label="Kontak operandı / tag" value={selected.tag} options={bools} disabled={locked} onChange={tag=>modify(e=>({...e,tag} as Expr))}/></>}{'pt'in selected&&<label>PT (ms)<input disabled={locked} type="number" min="0" max="3600000" value={selected.pt} onChange={e=>modify(x=>({...x,pt:Number(e.target.value)} as Expr))}/></label>}{(selected.type==='CTU'||selected.type==='CTD'||selected.type==='CTUD')&&<fieldset disabled={locked} className="counter-properties"><Choice label="Sayaç instruction" value={selected.type} options={['CTU','CTD','CTUD']} onChange={type=>modify(e=>{const fresh=logicInstruction(type as 'CTU'|'CTD'|'CTUD',tags) as CounterExpr;return {...fresh,id:e.id,instance:(e as CounterExpr).instance,pv:(e as CounterExpr).pv,input:(e as CounterExpr).input};})}/><label>Instance adı<input aria-label="Sayaç instance adı" value={selected.instance??''} onChange={event=>modify(e=>({...e,instance:event.target.value} as Expr))}/></label><label>PV operandı<ValueEditor value={typeof selected.pv==='number'?{kind:'literal',value:selected.pv}:selected.pv} tags={tags} onChange={pv=>modify(e=>({...e,pv} as Expr))}/></label><small>BOOL çıkışlar: {selected.instance}.{selected.type==='CTUD'?'QU / QD':'Q'} · Sayısal çıkış: {selected.instance}.CV</small></fieldset>}{selected.type==='COMPARE'&&<fieldset disabled={locked}><Choice label="Karşılaştırma" value={selected.op} options={['==','<>','>','<','>=','<=']} onChange={op=>modify(e=>({...e,op} as Expr))}/><ValueEditor value={selected.a} tags={tags} onChange={a=>modify(e=>({...e,a} as Expr))}/><ValueEditor value={selected.b} tags={tags} onChange={b=>modify(e=>({...e,b} as Expr))}/></fieldset>}{'children'in selected&&<Choice label="Grup mantığı" value={selected.type} options={['AND','OR']} disabled={locked} onChange={type=>modify(e=>({...e,type} as Expr))}/>}<button onClick={()=>onWhy(selected.id)}>Why TRUE / FALSE?</button></>:<><Choice label="Çıkış instruction" value={n.output.type} options={['COIL','SET','RESET','MOVE']} disabled={locked} onChange={type=>update(n.id,{output:{...n.output,unassigned:false,type:type as Network['output']['type'],value:n.output.value??{kind:'literal',value:0}}})}/><Choice label="Çıkış tag" value={n.output.tag} options={outTags.filter(t=>n.output.type==='MOVE'?t.type!=='BOOL':t.type==='BOOL').map(t=>t.name)} disabled={locked} onChange={tag=>update(n.id,{output:{...n.output,tag}})}/>{n.output.type==='MOVE'&&<fieldset disabled={locked}><ValueEditor value={n.output.value??{kind:'literal',value:0}} tags={tags} onChange={value=>update(n.id,{output:{...n.output,value}})}/></fieldset>}</>}</div>}
 </div>;
}






