'use client';
import {useState,useEffect} from 'react';
import {createPortal} from 'react-dom';
import {Plus,Trash2,ArrowUp,ArrowDown,GitBranch,MousePointer2} from 'lucide-react';
import {blankNetwork,walk,type CounterExpr,type TimerExpr,type Expr,type Network,type Tag,type Trace,type Value} from '../plc/model';
import {connectBranch} from '../plc/connections';
import {useLang,useT} from '../i18n/react';
import {editorDict} from '../i18n/dict/editor';
import {find,replace,remove,insert,moveNode} from './editing';
import {Choice} from '../ui/Choice';
import {ValueEditor} from './ValueEditor';
import Rung from './Rung';
import {InstructionIcon,instructionHelp} from './InstructionIcon';
import {booleanOutput,logicInstruction,numericOutput,type NumericInstruction} from './instructionFactory';
type Props={inspectorTarget?:HTMLElement|null;onInspect?:()=>void;blockName?:string;zoom?:number;onCommandDone?:()=>void;command?:{kind:string;nonce:number};networks:Network[];tags:Tag[];trace:Record<string,Trace>;monitor:boolean;locked:boolean;onChange:(ns:Network[])=>void;onWhy:(id:string)=>void};
function TimeOperandEditor({value,tags,extra,onChange}:{value:number|Value;tags:Tag[];extra:string[];onChange:(value:Value)=>void}){const tt=useT(editorDict),operand:Value=typeof value==='number'?{kind:'literal',value}:value,mode=operand.kind==='tag'?'tag':'literal',timeTags=[...tags.filter(t=>t.type==='TIME').map(t=>t.name),...extra.filter(name=>name.endsWith('.ET'))];return <span className="time-operand-editor"><Choice label={tt('time.operandType')} value={mode} options={[{value:'literal',label:tt('value.literal')},{value:'tag',label:tt('value.tag')}]} onChange={kind=>onChange(kind==='tag'?{kind:'tag',tag:timeTags[0]??''}:{kind:'literal',value:1000})}/>{mode==='literal'?<input aria-label={tt('time.duration')} type="number" min="0" max="2147483647" value={operand.kind==='literal'?operand.value:1000} onChange={event=>onChange({kind:'literal',value:Number(event.target.value)})}/>:<Choice label={tt('time.tag')} value={operand.kind==='tag'?operand.tag:''} options={timeTags} onChange={tag=>onChange({kind:'tag',tag})}/>}</span>;}
export default function Editor({inspectorTarget,onInspect,blockName,zoom=100,onCommandDone,command,networks,tags,trace,monitor,locked,onChange,onWhy}:Props){
 const tt=useT(editorDict),{lang}=useLang(),[connectionMessage,setConnectionMessage]=useState<{error:string}|'done'|null>(null);
 const [selection,setSelection]=useState<{network:string;node:string;before?:boolean}>({network:'',node:''});const [palette,setPalette]=useState('NO');const [collapsed,setCollapsed]=useState<Set<string>>(()=>new Set());
 const n=networks.find(x=>x.id===selection.network),selected=n?find(n.logic,selection.node):undefined;
 const instanceBools:string[]=[],instanceNumbers:string[]=[];for(const network of networks)walk(network.logic,e=>{if((e.type==='CTU'||e.type==='CTD'||e.type==='CTUD')&&e.instance){if(e.type==='CTUD')instanceBools.push(`${e.instance}.QU`,`${e.instance}.QD`);else instanceBools.push(`${e.instance}.Q`);instanceNumbers.push(`${e.instance}.CV`);}if((e.type==='TON'||e.type==='TOF'||e.type==='TP')&&e.instance){instanceBools.push(`${e.instance}.Q`);instanceNumbers.push(`${e.instance}.ET`);}});const bools=[...tags.filter(t=>t.type==='BOOL').map(t=>t.name),...new Set(instanceBools)],outTags=tags.filter(t=>!t.address.startsWith('%I'));
 const update=(id:string,changes:Partial<Network>)=>onChange(networks.map(x=>x.id===id?{...x,...changes}:x));
 const modify=(change:(e:Expr)=>Expr)=>{if(n&&selected)update(n.id,{logic:replace(n.logic,selected.id,change)});};
 const make=(kind=palette):Expr=>logicInstruction(kind as Parameters<typeof logicInstruction>[0],tags);
 const add=(parallel=false,kind=palette)=>{const target=n??networks[networks.length-1];const node=make(kind);if(!target){const net=blankNetwork(outTags.find(t=>t.type==='BOOL')?.name);net.logic=node;onChange([...networks,net]);setSelection({network:net.id,node:node.id});}else{update(target.id,{logic:insert(target.logic,selected?.id,node,parallel,selection.before)});setSelection({network:target.id,node:node.id});}};
 useEffect(()=>{if(!command||locked)return;const kind=command.kind;if(['COIL','SET','RESET','MOVE','ADD','SUB','MUL','DIV','INT_TO_REAL','REAL_TO_INT','WORD_TO_INT','NORM_X','SCALE_X'].includes(kind)){const target=n??networks[networks.length-1]??blankNetwork();const output:Network['output']=['COIL','SET','RESET'].includes(kind)?booleanOutput(kind as 'COIL'|'SET'|'RESET',tags,target.output):numericOutput(kind as NumericInstruction,tags,target.output);if(networks.some(x=>x.id===target.id))update(target.id,{output});else onChange([...networks,{...target,output}]);setSelection({network:target.id,node:target.id});}else if(kind.startsWith('CMP ')){const target=n??networks[networks.length-1]??blankNetwork();const node=logicInstruction('COMPARE',tags,kind.slice(4) as '=='|'<>'|'>'|'<'|'>='|'<=');if(networks.some(x=>x.id===target.id))update(target.id,{logic:insert(target.logic,selected?.id,node,false,selection.before)});else onChange([...networks,{...target,logic:node}]);setSelection({network:target.id,node:node.id});}else add(false,kind);onCommandDone?.();},[command?.nonce]);
 return <div className="ladder-editor"><div className="instruction-ribbon"><div className="ribbon-group"><small>{tt('ribbon.contacts')}</small><div>{[['NO','—| |—'],['NC','—|/|—'],['R_TRIG','—|P|—'],['F_TRIG','—|N|—']].map(([kind,symbol])=><button key={kind} disabled={locked} title={instructionHelp(kind,lang)} aria-label={kind} onClick={()=>{setPalette(kind);add(false,kind);}}><InstructionIcon kind={kind}/><span>{kind}</span></button>)}</div></div><div className="ribbon-group"><small>{tt('ribbon.coils')}</small><div>{[['COIL','—( )—'],['SET','—(S)—'],['RESET','—(R)—']].map(([kind,symbol])=><button key={kind} title={instructionHelp(kind,lang)} aria-label={kind} disabled={locked} onClick={()=>{const target=n??networks[networks.length-1];if(target){update(target.id,{output:{...target.output,unassigned:false,type:kind as Network['output']['type']}});setSelection({network:target.id,node:target.id});}else{const net=blankNetwork(outTags.find(t=>t.type==='BOOL')?.name);net.output.unassigned=false;net.output.type=kind as Network['output']['type'];onChange([...networks,net]);setSelection({network:net.id,node:net.id});}}}><InstructionIcon kind={kind}/><span>{kind}</span></button>)}</div></div><div className="ribbon-group"><small>{tt('ribbon.timersCounters')}</small><div>{['TON','TOF','TP','CTU','CTD','CTUD'].map(kind=><button key={kind} title={instructionHelp(kind,lang)} aria-label={kind} disabled={locked} onClick={()=>{setPalette(kind);add(false,kind);}}><InstructionIcon kind={kind}/><span>{tt(kind.startsWith('CT')?'ribbon.counter':'ribbon.timer')}</span></button>)}</div></div><div className="ribbon-group"><small>{tt('ribbon.branchCompare')}</small><div><button title={tt('ribbon.addParallel')} aria-label={tt('ribbon.addParallel')} disabled={locked} onClick={()=>add(true,'NO')}><GitBranch size={22}/><span>{tt('ribbon.parallel')}</span></button><button title={tt('ribbon.addSeries')} aria-label={tt('ribbon.addSeries')} disabled={locked} onClick={()=>add(false,'NO')}><Plus size={22}/><span>{tt('ribbon.series')}</span></button><button disabled={locked} onClick={()=>add(false,'COMPARE')}><strong>≥ ≤</strong><span>{tt('ribbon.compare')}</span></button><button disabled={locked||!selected} onClick={()=>{if(n)update(n.id,{logic:remove(n.logic,selection.node)});}} aria-label={tt('ribbon.deleteSelected')}><Trash2 size={22}/><span>{tt('ribbon.delete')}</span></button></div></div></div><div className="ribbon-secondary"><MousePointer2 size={13}/><span>{tt('ribbon.hint')}</span><button disabled={locked||!n} onClick={()=>{if(n){update(n.id,{output:{type:'MOVE',tag:'TEMP',value:{kind:'literal',value:0}}});setSelection({network:n.id,node:n.id});}}}>{tt('ribbon.moveMath')}</button></div>
 {connectionMessage&&<div role="status" className="connection-message">{connectionMessage==='done'?tt('conn.done'):connectionMessage.error}</div>}<div className="block-title">▾ <b>{tt('block.title')}</b> “{blockName??tt('block.default')}”</div><div className="block-comment">{tt('comment')}</div><div className="ladder-canvas">{networks.length===0&&<div className="empty-editor"><GitBranch size={32}/><h2>{tt('empty.heading')}</h2><p>{tt('empty.text')}</p><button className="primary" onClick={()=>onChange([blankNetwork(outTags.find(t=>t.type==='BOOL')?.name)])} disabled={locked}>{tt('empty.add')}</button></div>}
 {networks.map((net,index)=>{const isCollapsed=collapsed.has(net.id);return <section className={`network${isCollapsed?' network-collapsed':''}`} id={`network-${net.id}`} key={net.id}><div className="networkhead"><button className="network-collapse" aria-label={tt(isCollapsed?'network.expand':'network.collapse',{n:index+1})} onClick={()=>setCollapsed(current=>{const next=new Set(current);if(next.has(net.id))next.delete(net.id);else next.add(net.id);return next;})}>{isCollapsed?'▸':'▾'}</button><b>{tt('network.label',{n:index+1})}</b><input aria-label={tt('network.title',{n:index+1})} value={net.title} disabled={locked} onChange={e=>update(net.id,{title:e.target.value})}/><button aria-label={tt('network.up')} disabled={locked||index===0} onClick={()=>{const ns=[...networks];[ns[index-1],ns[index]]=[ns[index],ns[index-1]];onChange(ns);}}><ArrowUp size={13}/></button><button aria-label={tt('network.down')} disabled={locked||index===networks.length-1} onClick={()=>{const ns=[...networks];[ns[index+1],ns[index]]=[ns[index],ns[index+1]];onChange(ns);}}><ArrowDown size={13}/></button><button aria-label={tt('network.delete')} disabled={locked} onClick={()=>onChange(networks.filter(x=>x.id!==net.id))}><Trash2 size={13}/></button></div>{!isCollapsed&&<><input className="network-comment" aria-label={tt('network.comment',{n:index+1})} placeholder={tt('comment')} value={net.comment??''} disabled={locked} onChange={e=>update(net.id,{comment:e.target.value})}/><div className="rung-scroll"><div style={{zoom:zoom/100}}><Rung network={net} tags={tags} trace={trace} monitor={monitor} locked={locked} selected={selection.node} onSelect={id=>{setSelection({network:net.id,node:id});onInspect?.();}} onWhy={onWhy} onInsert={(id,before)=>setSelection({network:net.id,node:id,before})} onTag={(id,tag)=>id===net.id?update(net.id,{output:{...net.output,unassigned:false,tag}}):update(net.id,{logic:replace(net.logic,id,e=>({...e,tag} as Expr))})} onOperand={(id,field,value)=>update(net.id,{logic:replace(net.logic,id,e=>({...e,[field]:value} as Expr))})} onConnect={connection=>{try{const updated=connectBranch(net,connection,lang);onChange(networks.map(n=>n.id===net.id?updated:n));setConnectionMessage('done');}catch(error){setConnectionMessage({error:error instanceof Error?error.message:String(error)});}}} onDisconnect={(block,pin)=>update(net.id,{connections:(net.connections??[]).filter(c=>c.block!==block||c.pin!==pin)})} onMove={(a,b)=>update(net.id,{logic:moveNode(net.logic,a,b)})}/></div></div>{monitor&&trace[net.id]&&<div className="network-trace">{trace[net.id].detail}</div>}</>}</section>})}{networks.length>0&&<button className="add-network" disabled={locked} onClick={()=>onChange([...networks,blankNetwork(outTags.find(t=>t.type==='BOOL')?.name)])}><Plus size={15}/>{tt('network.add')}</button>}</div>
 {n&&inspectorTarget&&createPortal(<div className="instruction-inspector">
  <b>{tt('inspector.title')}</b>
  {selected?<>
   <span className="pill">{selected.type}</span>
   {'tag'in selected&&<><Choice label={tt('inspector.contactType')} value={selected.type} options={['NO','NC','P','N']} disabled={locked} onChange={type=>modify(e=>({...e,type} as Expr))}/><Choice label={tt('inspector.contactOperand')} value={selected.tag} options={bools} disabled={locked} onChange={tag=>modify(e=>({...e,tag} as Expr))}/></>}
   {(selected.type==='TON'||selected.type==='TOF'||selected.type==='TP')&&<fieldset disabled={locked} className="timer-properties"><Choice label={tt('inspector.timerInstruction')} value={selected.type} options={['TON','TOF','TP']} onChange={type=>modify(e=>{const fresh=logicInstruction(type as 'TON'|'TOF'|'TP',tags) as TimerExpr;return {...fresh,id:e.id,instance:(e as TimerExpr).instance,pt:(e as TimerExpr).pt,input:(e as TimerExpr).input};})}/><label>{tt('inspector.instanceName')}<input aria-label={tt('inspector.timerInstance')} value={selected.instance??''} onChange={event=>modify(e=>({...e,instance:event.target.value} as Expr))}/></label><label>{tt('inspector.ptOperand')}<TimeOperandEditor value={selected.pt} tags={tags} extra={instanceNumbers} onChange={pt=>modify(e=>({...e,pt} as Expr))}/></label><small>{tt('inspector.timerOutputs',{instance:selected.instance??''})}</small></fieldset>}
   {(selected.type==='CTU'||selected.type==='CTD'||selected.type==='CTUD')&&<fieldset disabled={locked} className="counter-properties"><Choice label={tt('inspector.counterInstruction')} value={selected.type} options={['CTU','CTD','CTUD']} onChange={type=>modify(e=>{const fresh=logicInstruction(type as 'CTU'|'CTD'|'CTUD',tags) as CounterExpr;return {...fresh,id:e.id,instance:(e as CounterExpr).instance,pv:(e as CounterExpr).pv,input:(e as CounterExpr).input};})}/><label>{tt('inspector.instanceName')}<input aria-label={tt('inspector.counterInstance')} value={selected.instance??''} onChange={event=>modify(e=>({...e,instance:event.target.value} as Expr))}/></label><label>{tt('inspector.pvOperand')}<ValueEditor value={typeof selected.pv==='number'?{kind:'literal',value:selected.pv}:selected.pv} tags={tags} extraNumeric={instanceNumbers} onChange={pv=>modify(e=>({...e,pv} as Expr))}/></label><small>{tt('inspector.counterOutputs',{instance:selected.instance??'',bool:selected.type==='CTUD'?'QU / QD':'Q'})}</small></fieldset>}
   {selected.type==='COMPARE'&&<fieldset disabled={locked}><Choice label={tt('inspector.comparison')} value={selected.op} options={['==','<>','>','<','>=','<=']} onChange={op=>modify(e=>({...e,op} as Expr))}/><ValueEditor value={selected.a} tags={tags} extraNumeric={instanceNumbers} onChange={a=>modify(e=>({...e,a} as Expr))}/><ValueEditor value={selected.b} tags={tags} extraNumeric={instanceNumbers} onChange={b=>modify(e=>({...e,b} as Expr))}/></fieldset>}
   {'children'in selected&&<Choice label={tt('inspector.groupLogic')} value={selected.type} options={['AND','OR']} disabled={locked} onChange={type=>modify(e=>({...e,type} as Expr))}/>}<button onClick={()=>onWhy(selected.id)}>{tt('inspector.why')}</button>
  </>:<><Choice label={tt('inspector.outputInstruction')} value={n.output.type} options={['COIL','SET','RESET','MOVE']} disabled={locked} onChange={type=>update(n.id,{output:{...n.output,unassigned:false,type:type as Network['output']['type'],value:n.output.value??{kind:'literal',value:0}}})}/><Choice label={tt('inspector.outputTag')} value={n.output.tag} options={outTags.filter(t=>n.output.type==='MOVE'?t.type!=='BOOL':t.type==='BOOL').map(t=>t.name)} disabled={locked} onChange={tag=>update(n.id,{output:{...n.output,tag}})}/>{n.output.type==='MOVE'&&<fieldset disabled={locked}><ValueEditor value={n.output.value??{kind:'literal',value:0}} tags={tags} extraNumeric={instanceNumbers} onChange={value=>update(n.id,{output:{...n.output,value}})}/></fieldset>}</>}
 </div>,inspectorTarget)}
 </div>;
}






