'use client';
import {useRef,useState} from 'react';
import {walk,type Expr,type Network,type Tag,type Trace,type Value} from '../plc/model';
import {layoutRung,LAD_GRID_X,LAD_GRID_Y,type LogicLayout} from './geometry';
import LadSymbol from './LadSymbol';
import {formatTimeOperand,numericOperand,timeOperand} from './inlineOperands';

type OperandField='pt'|'pv'|'etTag'|'cvTag';
interface Props {network:Network;tags:Tag[];trace:Record<string,Trace>;monitor:boolean;locked:boolean;selected:string;onSelect:(id:string)=>void;onWhy:(id:string)=>void;onMove:(from:string,to:string)=>void;onTag:(id:string,tag:string)=>void;onOperand:(id:string,field:OperandField,value:Value|string)=>void;onInsert:(id:string,before:boolean)=>void}
const valueText=(v:Value):string=>v.kind==='tag'?v.tag:v.kind==='literal'?String(v.value):`${v.op}(${valueText(v.a)}, ${valueText(v.b)}${v.c?', '+valueText(v.c):''})`;
const counterValueText=(v:number|Value):string=>typeof v==='number'?String(v):valueText(v);
const timeValueText=(v:number|Value):string=>v&&typeof v==='object'&&v.kind==='calc'?valueText(v):formatTimeOperand(v);

export default function Rung({network,tags,trace,monitor,locked,selected,onSelect,onWhy,onMove,onTag,onOperand,onInsert}:Props){
 const layout=layoutRung(network),drag=useRef<{id:string;x:number;y:number}|null>(null),[dragging,setDragging]=useState(''),[tagEdit,setTagEdit]=useState<{id:string;x:number;y:number;value:string}|null>(null),[operandEdit,setOperandEdit]=useState<{id:string;field:OperandField;x:number;y:number;value:string}|null>(null);
 const counterOperands:string[]=[];walk(network.logic,e=>{if((e.type==='CTU'||e.type==='CTD'||e.type==='CTUD')&&e.instance){if(e.type==='CTUD')counterOperands.push(`${e.instance}.QU`,`${e.instance}.QD`);else counterOperands.push(`${e.instance}.Q`);}if((e.type==='TON'||e.type==='TOF'||e.type==='TP')&&e.instance)counterOperands.push(`${e.instance}.Q`);});
 const online=monitor&&Object.keys(trace).length>0;
 const color=(powered:boolean)=>online?(powered?'#168b42':'#202A33'):'#202A33';
 const wire=(x1:number,y1:number,x2:number,y2:number,powered:boolean,key?:string)=><line key={key} x1={x1} y1={y1} x2={x2} y2={y2} stroke={color(powered)} strokeWidth={2} vectorEffect="non-scaling-stroke"/>;
 const label=(tag:string,x:number,y:number,id:string)=>{const physical=tags.find(t=>t.name===tag),virtual=/\.(Q|QU|QD)$/i.test(tag);const address=physical?.address??(virtual?'IEC counter':'???');return <g className="rung-tag" onClick={event=>{event.stopPropagation();onSelect(id);if(!locked)setTagEdit({id,x,y,value:tag});}}><title>{`${address} ${tag}`}</title><rect x={x-LAD_GRID_X/2} y={y-13} width={LAD_GRID_X} height={37} fill="transparent" style={{cursor:'text'}}/><svg x={x-LAD_GRID_X/2} y={y-13} width={LAD_GRID_X} height={36} overflow="hidden"><text x={LAD_GRID_X/2} y={13} textAnchor="middle" className="rung-address">{address}</text><text x={LAD_GRID_X/2} y={31} textAnchor="middle">{tag?`"${tag}"`:'???'}</text></svg></g>;};
 const hit=(id:string,x:number,y:number,width:number,height:number,title:string)=><rect x={x} y={y} width={width} height={height} fill={selected===id?'#e4f2fc':'transparent'} stroke={selected===id?'#70a8cd':'transparent'} className="rung-hit"><title>{title}</title></rect>;
 const openOperand=(event:React.MouseEvent,id:string,field:OperandField,x:number,y:number,value:string)=>{event.stopPropagation();if(!locked)setOperandEdit({id,field,x,y,value});};
 function logicView(l:LogicLayout,x:number,y:number,powered:boolean,mainInput=false):React.ReactNode{
  const e=l.expr,ty=y+l.terminalY,q=!!trace[e.id]?.value;
  if('children'in e){
   if(!l.children.length&&e.pin&&!mainInput)return <g key={e.id} role="button" tabIndex={0} aria-label="Boş pin: kontak ekle" onClick={()=>onSelect(e.id)} onKeyDown={event=>{if(event.key==='Enter')onSelect(e.id);}}><rect x={x} y={ty-11} width={l.width} height={22} fill={selected===e.id?'#deeffb':'transparent'}/><text x={x+l.width-4} y={ty+4} textAnchor="end">false</text></g>;
   if(!l.children.length)return <g key={e.id} data-expr-id={e.id} role="button" tabIndex={0} aria-label="Boş yol: eleman eklemek için seç" onClick={()=>onSelect(e.id)} onKeyDown={ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();onSelect(e.id);}}}>{wire(x,ty,x+l.width,ty,powered)}<rect x={x} y={ty-10} width={l.width} height={20} fill="transparent"/><path className="insertion-marker" d={`M ${x+LAD_GRID_X/2-6} ${ty-9} h -5 v 18 h 5 M ${x+LAD_GRID_X/2+6} ${ty-9} h 5 v 18 h -5`} fill="none" stroke="#3186bc" strokeWidth={1.5}/></g>;
   if(e.type==='AND'){let incoming=powered;return <g key={e.id}>{l.children.map(child=>{const p=incoming;incoming=incoming&&!!trace[child.layout.expr.id]?.value;return logicView(child.layout,x+child.x,y+child.y,p);})}</g>;}
   const left=x+LAD_GRID_X,right=x+l.width-LAD_GRID_X,first=ty,last=y+l.children[l.children.length-1].y+l.children[l.children.length-1].layout.terminalY;
   return <g key={e.id}>{wire(x,first,left,first,powered)}{wire(right,first,x+l.width,first,powered&&q)}{wire(left,first,left,last,powered)}{wire(right,first,right,last,powered&&q)}{l.children.map(child=>{const py=y+child.y+child.layout.terminalY,childQ=!!trace[child.layout.expr.id]?.value;return <g key={child.layout.expr.id}>{wire(left,py,x+child.x,py,powered)}{logicView(child.layout,x+child.x,y+child.y,powered)}{wire(x+child.x+child.layout.width,py,right,py,powered&&childQ)}<circle cx={left} cy={py} r={3} fill={color(powered)}/><circle cx={right} cy={py} r={3} fill={color(powered&&childQ)}/></g>;})}</g>;
  }
  const behavior={onClick:()=>onSelect(e.id),onContextMenu:(event:React.MouseEvent)=>{event.preventDefault();onWhy(e.id);},onKeyDown:(event:React.KeyboardEvent)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(e.id);}if(event.key==='F1'){event.preventDefault();onWhy(e.id);}}};
  if('tag'in e){const cx=x+LAD_GRID_X/2;return <g key={e.id} data-expr-id={e.id} role="button" tabIndex={0} aria-label={`${e.type} ${e.tag}`} {...behavior}>{hit(e.id,cx-15,ty-14,30,28,e.type+' '+e.tag)}{label(e.tag,cx,ty-38,e.id)}<LadSymbol kind={e.type} x={x} y={ty-LAD_GRID_Y/2} incoming={color(powered)} outgoing={color(powered&&q)}/></g>;}
  if(e.type==='R_TRIG'||e.type==='F_TRIG'){const bx=x+l.boxX!,cx=bx+LAD_GRID_X/2;return <g key={e.id}>{l.children.map(c=>logicView(c.layout,x+c.x,y+c.y,powered))}<g data-expr-id={e.id} role="button" tabIndex={0} aria-label={e.type} {...behavior}>{hit(e.id,cx-15,ty-14,30,28,e.type)}<text x={cx} y={ty-24} textAnchor="middle">{e.type==='R_TRIG'?'P_TRIG':'N_TRIG'}</text><LadSymbol kind={e.type==='R_TRIG'?'P':'N'} x={bx} y={ty-LAD_GRID_Y/2} incoming={color(powered&&!!trace[e.input.id]?.value)} outgoing={color(powered&&q)}/></g></g>;}
  if(e.type==='COMPARE'){const cx=x+l.width/2;return <g key={e.id} data-expr-id={e.id} role="button" tabIndex={0} aria-label={`Compare ${e.op}`} {...behavior}>{hit(e.id,x+4,y+2,l.width-8,124,'Karşılaştırma özellikleri')}{wire(x,ty,cx-28,ty,powered)}{wire(cx+28,ty,x+l.width,ty,powered&&q)}{wire(cx-28,ty-16,cx-28,ty+16,powered&&q)}{wire(cx+28,ty-16,cx+28,ty+16,powered&&q)}<text x={cx} y={ty-29} textAnchor="middle">{valueText(e.a)}</text><text x={cx} y={ty+5} textAnchor="middle">{e.op}</text><text x={cx} y={ty+38} textAnchor="middle">{valueText(e.b)}</text></g>;}
  const bx=x+l.boxX!,right=x+l.width-16,top=ty-26,bottom=Math.max(ty+80,l.resetY===undefined?0:y+l.resetY+80);
  const isCounter=e.type==='CTU'||e.type==='CTD'||e.type==='CTUD',isInstance=isCounter||'pt'in e;
  return <g key={e.id}>{l.children.map(child=>{const py=y+child.y+child.layout.terminalY,control=child.port!=='IN'&&child.port!=='CU'&&(e.type!=='CTD'||child.port!=='CD');return <g key={child.layout.expr.id}>{logicView(child.layout,x+child.x,y+child.y,control?true:powered,!control)}{wire(x+child.x+child.layout.width,py,bx,py,control?!!trace[child.layout.expr.id]?.value:powered&&!!trace[child.layout.expr.id]?.value)}</g>;})}<g data-expr-id={e.id} role="button" tabIndex={0} aria-label={`${e.type} instruction`} {...behavior}>{isInstance&&<text x={(bx+right)/2} y={top-8} textAnchor="middle" className="rung-address">{e.instance??'???'}</text>}<rect x={bx} y={top} width={right-bx} height={bottom-top} fill={selected===e.id?'#deeffb':'#dedee8'} stroke={selected===e.id?'#6e9fc0':'#b9bdca'}/><rect x={bx} y={top} width={right-bx} height={22} fill="#c9cbd9"/><text x={(bx+right)/2} y={top+16} textAnchor="middle" fontWeight="600">{e.type}</text>{l.children.map(child=><text key={child.port} x={bx+6} y={y+child.y+child.layout.terminalY+5}>{child.port}</text>)}<text x={right-6} y={ty+5} textAnchor="end">{e.type==='CTUD'?'QU':'Q'}</text>{e.type==='CTUD'&&<text x={right-6} y={ty+29} textAnchor="end">QD</text>}{'pt'in e&&<><text x={bx+8} y={ty+29}>PT  {timeValueText(e.pt)}</text><rect role="button" tabIndex={0} aria-label="PT operandını düzenle" x={bx+2} y={ty+11} width={right-bx-4} height={24} fill="transparent" className="operand-hit" onPointerDown={event=>event.stopPropagation()} onDoubleClick={event=>openOperand(event,e.id,'pt',bx+8,ty+12,timeValueText(e.pt))}/><text x={right-6} y={ty+49} textAnchor="end">ET  {e.etTag||'???'}</text><rect role="button" tabIndex={0} aria-label="ET çıkış tagini düzenle" x={bx+2} y={ty+34} width={right-bx-4} height={23} fill="transparent" className="operand-hit" onPointerDown={event=>event.stopPropagation()} onDoubleClick={event=>openOperand(event,e.id,'etTag',bx+8,ty+35,e.etTag??'')}/></>}{'pv'in e&&<><text x={bx+8} y={bottom-27}>PV  {counterValueText(e.pv)}</text><rect role="button" tabIndex={0} aria-label="PV operandını düzenle" x={bx+2} y={bottom-45} width={right-bx-4} height={24} fill="transparent" className="operand-hit" onPointerDown={event=>event.stopPropagation()} onDoubleClick={event=>openOperand(event,e.id,'pv',bx+8,bottom-44,counterValueText(e.pv))}/><text x={right-6} y={bottom-7} textAnchor="end">CV  {e.cvTag||'???'}</text><rect role="button" tabIndex={0} aria-label="CV çıkış tagini düzenle" x={bx+2} y={bottom-24} width={right-bx-4} height={23} fill="transparent" className="operand-hit" onPointerDown={event=>event.stopPropagation()} onDoubleClick={event=>openOperand(event,e.id,'cvTag',bx+8,bottom-23,e.cvTag??'')}/></>}<text x={bx+8} y={ty+68} className="rung-block-state">{online?(trace[e.id]?.detail.match(/ET=\S+|CV=\S+/)?.[0]??`Q=${q}`):''}</text><title>{trace[e.id]?.detail??e.type}</title></g>{wire(right,ty,x+l.width,ty,powered&&q)}</g>;
 }
 function insertionPoints(l:LogicLayout,x:number,y:number):React.ReactNode{return <g>{l.children.map(c=><g key={c.layout.expr.id}>{insertionPoints(c.layout,x+c.x,y+c.y)}</g>)}{!('children'in l.expr)&&[true,false].map(before=>{const px=before?x+3:x+l.width-3,py=y+l.terminalY;return <g key={String(before)} className="wire-slot" role="button" tabIndex={0} aria-label={before?'Önüne ekle':'Arkasına ekle'} onClick={()=>onInsert(l.expr.id,before)} onKeyDown={e=>{if(e.key==='Enter')onInsert(l.expr.id,before);}}><rect x={px-6} y={py-10} width={12} height={20} fill="transparent"/><path d={`M ${px-4} ${py-7} v 14 M ${px+4} ${py-7} v 14`} stroke="#3186bc" fill="none"/></g>;})}</g>;}
 const y=layout.terminalY,cx=layout.coilX+layout.coilWidth/2,power=!!trace[network.id]?.value;
 return <svg className="rung-svg" width={layout.width} height={layout.height} viewBox={`0 0 ${layout.width} ${layout.height}`} role="group" aria-label={`${network.title} Ladder network`} onPointerDown={event=>{if(locked)return;const id=(event.target as Element).closest('[data-expr-id]')?.getAttribute('data-expr-id');if(id){drag.current={id,x:event.clientX,y:event.clientY};setDragging(id);}}} onPointerUp={event=>{const start=drag.current;drag.current=null;setDragging('');if(!start||locked)return;const target=(event.target as Element).closest('[data-expr-id]')?.getAttribute('data-expr-id');if(target&&target!==start.id&&Math.hypot(event.clientX-start.x,event.clientY-start.y)>6)onMove(start.id,target);}} onPointerLeave={()=>{drag.current=null;setDragging('');}}>
  {wire(LAD_GRID_X,LAD_GRID_Y/2,LAD_GRID_X,layout.height-LAD_GRID_Y/2,power)}{wire(LAD_GRID_X,y,layout.logicX,y,power)}{logicView(layout.logic,layout.logicX,layout.logicY,true)}{wire(layout.logicX+layout.logic.width,y,layout.coilX,y,power)}
  {network.output.unassigned?wire(layout.coilX,y,layout.coilX+layout.coilWidth,y,power):<g role="button" tabIndex={0} aria-label={`${network.output.type} ${network.output.tag}`} onClick={()=>onSelect(network.id)} onContextMenu={event=>{event.preventDefault();onWhy(network.id);}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(network.id);}}}>{hit(network.id,cx-15,y-14,30,28,'Bobin / çıkış özellikleri')}{label(network.output.tag,cx,y-38,network.id)}{network.output.type==='MOVE'?<>{wire(layout.coilX,y,cx-48,y,power)}<rect x={cx-48} y={y-26} width={96} height={92} fill="#dedee8" stroke="#b5b9c7"/><rect x={cx-48} y={y-26} width={96} height={21} fill="#c5c7d2"/><text x={cx} y={y-11} textAnchor="middle">{network.output.value?.kind==='calc'?network.output.value.op:'MOVE'}</text><text x={cx-43} y={y+5}>EN</text><text x={cx+43} y={y+5} textAnchor="end">ENO</text><text x={cx-43} y={y+29}>IN</text><text x={cx+43} y={y+49} textAnchor="end">OUT1</text><line x1={cx-60} x2={cx-48} y1={y+25} y2={y+25} stroke="#b7a347" strokeWidth={2}/><line x1={cx+48} x2={cx+60} y1={y+45} y2={y+45} stroke="#b7a347" strokeWidth={2}/><text x={cx-53} y={y+20} textAnchor="end" className="rung-state">{network.output.value?valueText(network.output.value):'???'}</text>{wire(cx+48,y,layout.coilX+layout.coilWidth,y,power)}<title>{network.output.value?valueText(network.output.value):'MOVE'}</title></>:<LadSymbol kind={network.output.type} x={layout.coilX} y={y-LAD_GRID_Y/2} incoming={color(power)} outgoing={color(power)}/>}</g>}
  {wire(layout.coilX+layout.coilWidth,y,layout.rightRailX,y,power)}{wire(layout.rightRailX,y-3,layout.rightRailX,y+3,power)}
 <g className="wire-slot" role="button" tabIndex={0} aria-label="Hat sonuna eleman ekle" onClick={()=>onInsert(network.logic.id,false)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();onInsert(network.logic.id,false);}}}><rect x={layout.coilX+layout.coilWidth} y={y-10} width={Math.max(0,layout.rightRailX-layout.coilX-layout.coilWidth)} height={20} fill="transparent"/><path d={`M ${layout.rightRailX-36} ${y-8} v 16 M ${layout.rightRailX-28} ${y-8} v 16`} fill="none" stroke="#168AC0"/></g>
 {insertionPoints(layout.logic,layout.logicX,layout.logicY)}
 {tagEdit&&<foreignObject x={Math.max(0,tagEdit.x-65)} y={tagEdit.y-17} width={190} height={62}><div className="inline-tag"><input autoFocus aria-label="Tag adı" list={`tags-${network.id}`} value={tagEdit.value} onChange={event=>setTagEdit({...tagEdit,value:event.target.value})} onKeyDown={event=>{event.stopPropagation();if(event.key==='Enter'){onTag(tagEdit.id,tagEdit.value);setTagEdit(null);}if(event.key==='Escape')setTagEdit(null);}} onBlur={()=>{onTag(tagEdit.id,tagEdit.value);setTagEdit(null);}}/><datalist id={`tags-${network.id}`}>{tags.filter(t=>tagEdit.id===network.id?!t.address.startsWith('%I'):t.type==='BOOL').map(t=><option key={t.name} value={t.name}>{t.address} · {t.type}</option>)}{tagEdit.id!==network.id&&counterOperands.map(name=><option key={name} value={name}>IEC counter output · BOOL</option>)}</datalist></div></foreignObject>}
 {operandEdit&&<foreignObject x={Math.max(0,operandEdit.x-4)} y={operandEdit.y} width={205} height={68}><div className="inline-tag"><input autoFocus aria-label={`${operandEdit.field.toUpperCase()} operand düzenleyici`} list={`operand-tags-${network.id}`} value={operandEdit.value} onChange={event=>setOperandEdit({...operandEdit,value:event.target.value})} onKeyDown={event=>{event.stopPropagation();if(event.key==='Enter'){const value=operandEdit.field==='pt'?timeOperand(operandEdit.value):operandEdit.field==='pv'?numericOperand(operandEdit.value):operandEdit.value.trim();onOperand(operandEdit.id,operandEdit.field,value);setOperandEdit(null);}if(event.key==='Escape')setOperandEdit(null);}} onBlur={()=>{const value=operandEdit.field==='pt'?timeOperand(operandEdit.value):operandEdit.field==='pv'?numericOperand(operandEdit.value):operandEdit.value.trim();onOperand(operandEdit.id,operandEdit.field,value);setOperandEdit(null);}}/><datalist id={`operand-tags-${network.id}`}>{tags.filter(t=>{if(operandEdit.field==='pt'||operandEdit.field==='etTag')return t.type==='TIME'&&(operandEdit.field==='pt'||!t.address.startsWith('%I'));return ['INT','DINT','WORD','DWORD'].includes(t.type)&&(operandEdit.field==='pv'||!t.address.startsWith('%I'));}).map(t=><option key={t.name} value={t.name}>{t.address} · {t.type}</option>)}</datalist><small>{operandEdit.field==='pt'?'T#3s, T#500ms veya TIME tag':operandEdit.field==='pv'?'Sayı veya integer tag':'Yazılabilir tag seçin'}</small></div></foreignObject>}
 </svg>;
}
